version = "1.0"

[metadata]
author_name = "Fred Amartey"
difficulty = "medium"
category = "software-engineering"
tags = ["typescript", "leglas", "bug-fix", "packages/server"]
fix_commit = "e02c9f561d4d934d76da12c5faa4c7712330e0bc"
base_commit = "de7b4f062ca710c5b252d8d62d3b16b78919adfc"

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 1500.0

[environment]
build_timeout_sec = 1800.0
cpus = 2
memory = "3G"
