import { basename, extname, normalize } from "node:path";

import { targetFor, type Preview } from "@leglas/server";

export type KeepPlan =
  | {
      ok: true;
      move: { from: string; to: string };
      removeDir: string;
      dropTitles: string[];
      exportName: string;
      instructions: string;
    }
  | { ok: false; error: string };

/** The surface a preview belongs to, read from the param the scaffold uses. */
function surfaceOf(url: string): string | null {
  if (!url.startsWith("/") || !url.includes("?")) return null;
  for (const pair of url.slice(url.indexOf("?") + 1).split("&")) {
    const key = pair.split("=")[0];
    if (key?.startsWith("v-")) return key.slice(2);
  }
  return null;
}

/** A component name derived from the destination filename. */
function exportNameFor(to: string): string {
  const stem = basename(to, extname(to));
  return stem
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

/**
 * Plan the end of an exploration.
 *
 * Exploring is only safe to start because finishing is cheap, and finishing
 * means the winner leaves the ignored directory for real source while the
 * alternatives disappear entirely. Leglas can do this only because it knows
 * where it put those files; anything it did not generate is refused rather than
 * guessed at.
 *
 * The one step left to the user is the import in their own component, for the
 * same reason `leglas new` prints it rather than applying it.
 */
export function planKeep(options: {
  title: string;
  previews: readonly Preview[];
  to: string;
}): KeepPlan {
  const winner = options.previews.find((preview) => preview.title === options.title);
  if (!winner) {
    return {
      ok: false,
      error: `No direction called ${JSON.stringify(options.title)}. Run npx leglas list to see them.`,
    };
  }

  const from = targetFor(winner.url);
  const surface = surfaceOf(winner.url);
  if (from === null || surface === null) {
    return {
      ok: false,
      error:
        `Cannot tell which file produces ${JSON.stringify(options.title)}. Its URL ` +
        `(${winner.url}) was not generated by leglas new, so there is nothing safe to move.`,
    };
  }

  const to = normalize(options.to);
  if (to.startsWith("..")) {
    return { ok: false, error: "The destination has to be inside the project." };
  }
  if (to.split(/[/\\]/)[0] === ".leglas") {
    return {
      ok: false,
      error: "The destination cannot be inside .leglas, which is ignored and gets deleted.",
    };
  }

  // Every direction of this surface goes, winner included: it is being kept as
  // ordinary code now, not as one of several alternatives.
  const dropTitles = options.previews
    .filter((preview) => surfaceOf(preview.url) === surface)
    .map((preview) => preview.title);

  const exportName = exportNameFor(to);

  return {
    ok: true,
    move: { from, to },
    removeDir: `.leglas/variants/${surface}`,
    dropTitles,
    exportName,
    instructions:
      `${options.title} now lives at ${to}, exported as ${exportName}. Point your ` +
      `component at it instead of the switcher, and the exploration is gone:\n\n` +
      `  <${exportName} />\n`,
  };
}
