export type Framework = "next" | "react";

export type Write = { path: string; contents: string };

export type NewPlan = {
  writes: Write[];
  /** New .gitignore contents, or null when no change is needed. */
  gitignore: string | null;
  previews: { title: string; url: string }[];
  instructions: string;
};

/**
 * Which shape of param reading to generate. Only the distinction that changes
 * the output is drawn: whether params arrive on the server as a prop, or are
 * read from the URL in the browser. The browser form is the fallback because
 * it works anywhere React does.
 */
export function detectFramework(packageJson: string | null): Framework {
  if (!packageJson) return "react";
  try {
    const parsed = JSON.parse(packageJson) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const deps = { ...parsed.dependencies, ...parsed.devDependencies };
    return "next" in deps ? "next" : "react";
  } catch {
    return "react";
  }
}

/** The surface name becomes a query param, so it has to survive a URL intact. */
export function surfaceSlug(surface: string): string {
  return surface
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

function titleCase(slug: string): string {
  return slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function nextSwitcher(slug: string): string {
  return `// Generated by leglas new. Plain application code: it imports nothing
// from Leglas, so deleting the tool leaves this working.
//
// Add a direction by dropping a component beside this file and listing it in
// DIRECTIONS. Everything renders from one running server, so switching is
// instant.
import { Current } from "./current";
import { ${titleCase(slug).replace(/\s/g, "")}A } from "./${slug}-a";

const DIRECTIONS = {
  current: Current,
  "${slug}-a": ${titleCase(slug).replace(/\s/g, "")}A,
} as const;

type Direction = keyof typeof DIRECTIONS;
const FALLBACK: Direction = "current";

type SearchParams = Record<string, string | string[] | undefined>;

/**
 * Production always renders the fallback, whatever the URL says, so a branch
 * point that reaches a deployed build cannot expose an unreleased direction.
 */
export function resolve${titleCase(slug).replace(/\s/g, "")}(searchParams: SearchParams): Direction {
  if (process.env.NODE_ENV === "production") return FALLBACK;
  const raw = searchParams["v-${slug}"];
  const value = Array.isArray(raw) ? raw[0] : raw;
  return value !== undefined && value in DIRECTIONS ? (value as Direction) : FALLBACK;
}

export function ${titleCase(slug).replace(/\s/g, "")}Switch({ searchParams }: { searchParams: SearchParams }) {
  const Direction = DIRECTIONS[resolve${titleCase(slug).replace(/\s/g, "")}(searchParams)];
  return <Direction />;
}
`;
}

function reactSwitcher(slug: string): string {
  const name = titleCase(slug).replace(/\s/g, "");
  return `// Generated by leglas new. Plain application code: it imports nothing
// from Leglas, so deleting the tool leaves this working.
//
// Add a direction by dropping a component beside this file and listing it in
// DIRECTIONS. Everything renders from one running server, so switching is
// instant.
import { Current } from "./current";
import { ${name}A } from "./${slug}-a";

const DIRECTIONS = {
  current: Current,
  "${slug}-a": ${name}A,
} as const;

type Direction = keyof typeof DIRECTIONS;
const FALLBACK: Direction = "current";

/**
 * Typed locally rather than relying on bundler-provided globals, so this file
 * compiles in any project without extra type packages installed.
 */
function isProduction(): boolean {
  const meta = import.meta as ImportMeta & { env?: { PROD?: boolean } };
  if (meta.env?.PROD === true) return true;
  const runtime = globalThis as { process?: { env?: { NODE_ENV?: string } } };
  return runtime.process?.env?.NODE_ENV === "production";
}

/**
 * Production always renders the fallback, whatever the URL says, so a branch
 * point that reaches a deployed build cannot expose an unreleased direction.
 */
export function resolve${name}(): Direction {
  if (isProduction()) return FALLBACK;
  const value = new URLSearchParams(window.location.search).get("v-${slug}");
  return value !== null && value in DIRECTIONS ? (value as Direction) : FALLBACK;
}

export function ${name}Switch() {
  const Direction = DIRECTIONS[resolve${name}()];
  return <Direction />;
}
`;
}

function placeholder(label: string, note: string): string {
  return `export function ${label}() {
  return (
    <div style={{ padding: "3rem", fontFamily: "system-ui" }}>
      <p>${note}</p>
    </div>
  );
}
`;
}

export function planNew(options: {
  surface: string;
  packageJson: string | null;
  gitignore: string | null;
}): NewPlan {
  const slug = surfaceSlug(options.surface);
  const framework = detectFramework(options.packageJson);
  const name = titleCase(slug).replace(/\s/g, "");
  const dir = `.leglas/variants/${slug}`;

  const writes: Write[] = [
    {
      path: `${dir}/switch.tsx`,
      contents: framework === "next" ? nextSwitcher(slug) : reactSwitcher(slug),
    },
    {
      path: `${dir}/current.tsx`,
      contents: placeholder(
        "Current",
        `Replace this with what your ${slug} renders today, then compare directions against it.`,
      ),
    },
    {
      path: `${dir}/${slug}-a.tsx`,
      contents: placeholder(`${name}A`, `A first direction for ${slug}. Change it and watch it reload.`),
    },
  ];

  // Only append when the entry is genuinely absent; rewriting a user's
  // .gitignore to add a duplicate line is the kind of small rudeness that
  // makes a tool feel careless.
  const hasEntry = (options.gitignore ?? "")
    .split("\n")
    .some((line) => line.trim() === ".leglas/" || line.trim() === ".leglas");
  const gitignore = hasEntry
    ? null
    : `${(options.gitignore ?? "").replace(/\n*$/, "")}\n\n# Leglas exploration: variant code, caches, logs.\n.leglas/\n`.replace(
        /^\n+/,
        "",
      );

  // Deliberately not a relative specifier. The depth depends on where the
  // user's component lives, and guessing it produces an import that looks
  // authoritative and does not resolve.
  const usage =
    framework === "next"
      ? `<${name}Switch searchParams={await searchParams} />`
      : `<${name}Switch />`;

  return {
    writes,
    gitignore,
    previews: [
      { title: "Current", url: `/?v-${slug}=current` },
      { title: `${titleCase(slug)} A`, url: `/?v-${slug}=${slug}-a` },
    ],
    instructions:
      `One change is left to you, where your ${slug} renders. Import ${name}Switch ` +
      `from ${dir}/switch and use it in place of the current element:\n\n  ${usage}\n\n` +
      `Rewriting your component automatically is how a tool breaks a codebase it ` +
      `does not understand, so this step stays yours.\n`,
  };
}
