import { boundPort, required } from "../test-helpers.js";
import { spawn } from "node:child_process";
import { EventEmitter } from "node:events";
import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import http from "node:http";
import { tmpdir } from "node:os";
import { PassThrough } from "node:stream";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { afterAll, describe, expect, test } from "vitest";

import { codexResultText, codexServers } from "./codex.js";
import { factsBlock, readProjectFacts } from "./facts.js";
import { createGenerations, type GenerationDeps } from "./generation.js";
import { addSlots } from "./switch-file.js";

import type { RunnerSpawn } from "../agents/runner.js";
import type { Preview } from "../config/config.js";
import type { AddInput } from "../config/local-previews.js";
import { START_TIMEOUT_MS, findBrowser } from "../capture/browser.js";
import { isJsonRecord, isString, parseJson, type JsonRecord, type JsonValue } from "../json.js";
import { startServer, type RunningServer } from "../server.js";

const ARTIFACTS = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "..",
  "test",
  "artifacts",
  "generation",
);

/** The switch file `leglas new hero` writes, trimmed to what a generation reads and edits. */
const SWITCH = `// Generated by leglas new.
import { Current } from "./current";
import { HeroA } from "./hero-a";

const DIRECTIONS = {
  current: Current,
  "hero-a": HeroA,
} as const;

type Direction = keyof typeof DIRECTIONS;
const FALLBACK: Direction = "current";

export function HeroSwitch() {
  const Direction = DIRECTIONS[FALLBACK];
  return <Direction />;
}
`;

/** A real current direction: what builders are shown as the house style. */
const CURRENT = `import { COPY } from "../../../src/copy";

export function Current() {
  return (
    <section style={{ background: "var(--ink)", color: "white", padding: 64 }}>
      <h1 style={{ fontFamily: "House Sans" }}>{COPY.headline}</h1>
      <p>{COPY.body}</p>
      <a href="#" style={{ color: "var(--accent)" }}>
        {COPY.cta}
      </a>
      <img src="/photos/plate.jpg" alt="" />
      <footer>Simmer</footer>
    </section>
  );
}
`;

const STYLES = `@font-face {
  font-family: "House Sans";
  src: url("/fonts/house.woff2") format("woff2");
}

:root {
  --ink: #101010;
  --accent: #d9542b;
}
`;

/**
 * Stands in for \`claude -p\`. A plan run answers with three concepts, or one
 * for a replacement; a build writes the file its prompt names, where "Broken"
 * writes a marker the dev server turns into a thrown error and "Slow" takes
 * long enough to be stopped; a fix run removes the marker. Every call's
 * arguments are logged so the test can read what Leglas sent.
 */
const FAKE_CLAUDE = `
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
const args = process.argv.slice(2);
const prompt = args[args.indexOf("-p") + 1] ?? "";
const tools = args[args.indexOf("--tools") + 1];
appendFileSync(process.env.FAKE_LOG, JSON.stringify({ args }) + "\\n");
const say = (event) => process.stdout.write(JSON.stringify(event) + "\\n");
const sleep = (ms) => new Promise((done) => setTimeout(done, ms));
say({ type: "system", subtype: "init", session_id: "fake" });
if (tools === "") {
  const one = /^Propose 1 /.test(prompt);
  const concepts = one
    ? [{ key: "fresh", title: "Fresh Idea", idea: "A replacement unlike the others." }]
    : [
        { key: "plain", title: "Plain Idea", idea: "Big type on a plain ground." },
        { key: "broken", title: "Broken Idea", idea: "Writes broken code first." },
        { key: "slow", title: "Slow Idea", idea: "Takes its time." },
      ];
  await sleep(150);
  say({ type: "result", subtype: "success", result: "Here you go:\\n\`\`\`json\\n" + JSON.stringify(concepts) + "\\n\`\`\`" });
  process.exit(0);
}
const fix = /^Leglas rendered (\\S+) and the page reported/.exec(prompt);
if (fix) {
  writeFileSync(fix[1], readFileSync(fix[1], "utf8").replace("// broken\\n", ""));
  say({ type: "result", subtype: "success", result: "fixed" });
  process.exit(0);
}
const file = /Your file is (\\S+)\\./.exec(prompt)[1];
const name = /component exported as (\\w+)\\./.exec(prompt)[1];
const title = /(?:direction for the \\w+|variation of the \\w+ direction "[^"]+"): ([^,]+),/.exec(prompt)[1];
readFileSync(file, "utf8");
if (title.startsWith("Slow")) writeFileSync(file, "// half written, as a stopped build leaves it\\n");
await sleep(title.startsWith("Slow") ? 20000 : 300);
const marker = title.startsWith("Broken") ? "// broken\\n" : "";
writeFileSync(file, marker + "// render: " + title + "\\nexport function " + name + "() {\\n  return <h1>" + title + "</h1>;\\n}\\n");
say({ type: "result", subtype: "success", result: "written" });
`;

const cleanups: (() => Promise<void>)[] = [];

afterAll(async () => {
  for (const cleanup of cleanups.splice(0).reverse()) await cleanup();
});

/** A project with a mounted hero switch, a stylesheet with tokens and one photograph. */
async function project(agent: string): Promise<string> {
  const cwd = await mkdtemp(join(tmpdir(), "leglas-generation-"));
  cleanups.push(() => rm(cwd, { recursive: true, force: true }));
  const variants = join(cwd, ".leglas", "variants", "hero");
  await mkdir(variants, { recursive: true });
  await mkdir(join(cwd, "src"), { recursive: true });
  await mkdir(join(cwd, "public", "photos"), { recursive: true });

  await writeFile(
    join(cwd, "package.json"),
    JSON.stringify({ dependencies: { react: "^19.2.0" }, devDependencies: { vite: "^7.1.0" } }),
  );

  await writeFile(join(cwd, "index.html"), '<script type="module" src="/src/main.tsx"></script>\n');
  await writeFile(join(cwd, "src", "main.tsx"), 'import "./styles.css";\n');
  await writeFile(join(cwd, "src", "styles.css"), STYLES);
  await writeFile(join(cwd, "public", "photos", "plate.jpg"), "not really a jpeg");
  await writeFile(join(variants, "switch.tsx"), SWITCH);
  await writeFile(join(variants, "current.tsx"), CURRENT);
  await writeFile(join(variants, "hero-a.tsx"), "export function HeroA() {\n  return null;\n}\n");
  await writeFile(join(cwd, ".leglas", "watch.json"), JSON.stringify({ agent }));

  return cwd;
}

/**
 * The app: renders a direction's file by its \`// render:\` line, and throws
 * for a file still carrying the broken marker, the way a transform error
 * reaches the page.
 */
async function devServer(cwd: string): Promise<number> {
  const server = http.createServer((req, res) => {
    void (async () => {
      const key = new URL(req.url ?? "/", "http://x").searchParams.get("v-hero") ?? "current";
      const source = await readFile(join(cwd, ".leglas", "variants", "hero", "switch.tsx"), "utf8");
      const name = new RegExp(`"?${key}"?:\\s*(\\w+)`).exec(source)?.[1] ?? "";

      const from =
        new RegExp(`import \\{ ${name} \\} from "\\./([^"]+)"`).exec(source)?.[1] ?? "current";

      const file = await readFile(
        join(cwd, ".leglas", "variants", "hero", `${from}.tsx`),
        "utf8",
      ).catch(() => "");

      const words = /\/\/ render: (.+)/.exec(file)?.[1] ?? "";

      const body = file.includes("// broken")
        ? '<script>throw new Error("Transform failed: unterminated JSX")</script>'
        : `<h1 style="font:48px system-ui;margin:48px">${words}</h1>`;

      res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
      res.end(`<!doctype html><html><body style="margin:0;background:#fff">${body}</body></html>`);
    })();
  });

  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  cleanups.push(
    () =>
      new Promise<void>((resolve) => {
        server.closeAllConnections();
        server.close(() => resolve());
      }),
  );

  return boundPort(server);
}

async function leglas(
  cwd: string,
  withBrowser: boolean,
  previews: Preview[] = [],
): Promise<{ server: RunningServer; log: string }> {
  const fake = join(cwd, "..", `${cwd.split("/").pop() ?? "x"}-fake-claude.mjs`);
  const log = `${fake}.log`;
  await writeFile(fake, FAKE_CLAUDE);
  await writeFile(log, "");
  cleanups.push(() => rm(fake, { force: true }));
  cleanups.push(() => rm(log, { force: true }));

  const fakeSpawn: RunnerSpawn = (_command, args, options) =>
    spawn(process.execPath, [fake, ...args], {
      ...options,
      env: { ...process.env, FAKE_LOG: log },
    });

  const serverOptions: Parameters<typeof startServer>[0] = {
    config: { devServer: `http://127.0.0.1:${await devServer(cwd)}`, previews },
    cwd,
    port: 0,
    codexAppServer: null,
    claudeAgentSession: null,
    detectTunnels: async () => [],
    generationSpawn: fakeSpawn,
  };

  // Refusals need no browser; only the end-to-end run renders anything.
  if (!withBrowser)
    serverOptions.pool = { acquire: async () => null, reason: () => "none", close: async () => {} };
  const server = await startServer(serverOptions);

  cleanups.push(() => server.close());

  return { server, log };
}

async function call(
  server: RunningServer,
  path: string,
  body?: JsonRecord,
): Promise<{ status: number; json: JsonRecord }> {
  const response = await fetch(`http://127.0.0.1:${server.port}/leglas/api/${path}`, {
    method: body === undefined ? "GET" : "POST",
    headers:
      body === undefined
        ? {}
        : { "content-type": "application/json", origin: `http://127.0.0.1:${server.port}` },
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  const json = parseJson(await response.text());

  return { status: response.status, json: isJsonRecord(json) ? json : {} };
}

type Job = {
  id: string;
  state: string;
  slots: { key: string; title: string; state: string; fixed: boolean }[];
};

function readJob(value: JsonValue | undefined): Job | null {
  if (
    !isJsonRecord(value) ||
    !isString(value.id) ||
    !isString(value.state) ||
    !Array.isArray(value.slots)
  )
    return null;

  return {
    id: value.id,
    state: value.state,
    slots: value.slots.filter(isJsonRecord).map((slot) => ({
      key: String(slot.key),
      title: String(slot.title),
      state: String(slot.state),
      fixed: slot.fixed === true,
    })),
  };
}

async function job(server: RunningServer): Promise<Job | null> {
  const { json } = await call(server, "generate");

  return Array.isArray(json.jobs) ? readJob(json.jobs.at(-1)) : null;
}

async function until(
  server: RunningServer,
  holds: (current: Job) => boolean,
  what: string,
): Promise<Job> {
  const deadline = Date.now() + 45_000;

  while (Date.now() < deadline) {
    const current = await job(server);

    if (current !== null && holds(current)) return current;
    await new Promise((resolve) => setTimeout(resolve, 100));
  }

  throw new Error(`Timed out waiting for ${what}: ${JSON.stringify(await job(server))}`);
}

describe("a switch file gaining slots", () => {
  test("keeps every direction it had and adds one import and entry per slot", () => {
    const result = addSlots(SWITCH, [{ key: "hero-plain", name: "HeroPlain" }]);

    expect(result).toContain(
      'import { HeroA } from "./hero-a";\nimport { HeroPlain } from "./hero-plain";\n',
    );
    expect(result).toContain(
      'const DIRECTIONS = {\n  current: Current,\n  "hero-a": HeroA,\n  "hero-plain": HeroPlain,\n} as const;',
    );
  });
});

describe("the facts a builder is given", () => {
  test("come from the project's stylesheet, public images and current direction", async () => {
    const cwd = await project("claude");
    const facts = await readProjectFacts(cwd, ".leglas/variants/hero/switch.tsx");

    expect(facts.dependencies).toEqual(["react"]);
    expect(facts.stylesheet?.path).toBe("src/styles.css");
    expect(facts.stylesheet?.fonts).toEqual(["House Sans"]);
    expect(facts.stylesheet?.tokens).toContain("--accent: #d9542b;");
    expect(facts.images).toEqual(["/photos/plate.jpg"]);
    expect(facts.example?.path).toBe(".leglas/variants/hero/current.tsx");
  });

  test("say where a long direction was cut, so a build never takes it for the whole", async () => {
    const cwd = await project("claude");
    const body = Array.from({ length: 698 }, (_, index) => `  // line ${index + 1}`);

    await writeFile(
      join(cwd, ".leglas", "variants", "hero", "hero-a.tsx"),
      ["export function HeroA() {", ...body, "}"].join("\n"),
    );

    const facts = await readProjectFacts(cwd, ".leglas/variants/hero/switch.tsx", "hero-a");
    const lines = facts.example?.source.split("\n") ?? [];

    expect(lines).toHaveLength(601);
    expect(lines.at(-1)).toBe("// … 100 more lines, not shown");

    // One line over, ending in a newline as files do: one line hidden, said as one.
    const one = ["export function HeroA() {", ...body.slice(0, 599), "}", ""].join("\n");
    await writeFile(join(cwd, ".leglas", "variants", "hero", "hero-a.tsx"), one);
    const cut = await readProjectFacts(cwd, ".leglas/variants/hero/switch.tsx", "hero-a");

    expect(cut.example?.source.split("\n").at(-1)).toBe("// … 1 more line, not shown");
  });

  test("name the example as the direction being varied only when it was read from it", async () => {
    const cwd = await project("claude");
    // Hero A is a stub, so the facts fall back to the current direction.
    const facts = await readProjectFacts(cwd, ".leglas/variants/hero/switch.tsx", "hero-a");
    const block = factsBlock(facts, "hero", { title: "Hero A", key: "hero-a" });

    expect(facts.example?.path).toBe(".leglas/variants/hero/current.tsx");
    expect(block).toContain(
      "The hero's current direction, .leglas/variants/hero/current.tsx, shows how directions here are written:",
    );
    expect(block).not.toContain("the direction being varied");
  });
});

describe("starting a generation", () => {
  test("is refused, with the reason, for an agent Leglas cannot hold to time", async () => {
    const { server } = await leglas(await project("cursor"), false);

    const started = await call(server, "generate", {
      surface: "hero",
      brief: "Dinner apps",
      count: 3,
    });

    expect(started.status).toBe(422);
    expect(String(started.json.error)).toBe(
      "Building directions runs on Claude or Codex. Choose one of them as the agent to use it.",
    );
  });

  test("is refused for a surface with no switch, naming the command that makes one", async () => {
    const { server } = await leglas(await project("claude"), false);

    const started = await call(server, "generate", {
      surface: "pricing",
      brief: "Plans",
      count: 3,
    });

    expect(started.status).toBe(422);
    expect(String(started.json.error)).toContain("leglas new pricing --from");
  });

  test("builds variations of a direction named as the rail names it, with no brief needed", async () => {
    const cwd = await project("claude");

    const { server, log } = await leglas(cwd, false, [
      { title: "Current", url: "/?v-hero=current", note: "Dark and type-led.", tags: [] },
      { title: "Elsewhere", url: "/pricing", tags: [] },
    ]);

    // No base, as the command line sends it for a new set, still needs a brief.
    const unbased = await call(server, "generate", {
      surface: "hero",
      brief: "",
      count: 2,
      basedOn: null,
    });

    expect(unbased.status).toBe(422);
    expect(unbased.json.error).toBe("Describe what the directions are for.");

    const blank = await call(server, "generate", {
      surface: "hero",
      brief: "",
      count: 2,
      basedOn: "",
    });

    expect(blank.json.error).toBe("Describe what the directions are for.");

    for (const basedOn of ["Nowhere", "Elsewhere"]) {
      const refused = await call(server, "generate", {
        surface: "hero",
        brief: "",
        count: 2,
        basedOn,
      });

      expect(refused.status).toBe(422);
      expect(String(refused.json.error)).toBe(
        `${basedOn} is not a direction of the hero, so Leglas cannot build variations of it.`,
      );
    }

    const started = await call(server, "generate", {
      surface: "hero",
      brief: "",
      count: 2,
      basedOn: "Current",
    });

    expect(started.status).toBe(202);
    expect(isJsonRecord(started.json.job) && started.json.job.basedOn).toBe("Current");

    let plan = "";

    for (let tries = 0; tries < 200 && plan === ""; tries += 1) {
      const first = (await readFile(log, "utf8")).split("\n")[0] ?? "";
      const args = first === "" ? [] : parseJson(first);
      const list = isJsonRecord(args) && Array.isArray(args.args) ? args.args.map(String) : [];
      plan = list[list.indexOf("-p") + 1] ?? "";

      if (plan === "") await new Promise((resolve) => setTimeout(resolve, 25));
    }

    expect(plan).toMatch(
      /^Propose 2 variations of the hero direction "Current" \(Dark and type-led\)\. Every variation stays recognisably Current/,
    );
  });
});

describe.skipIf(findBrowser() === null)("a generation, end to end", () => {
  test.skipIf(process.env.CODEX_SANDBOX === "seatbelt")(
    "plans, builds all at once, repairs a broken direction, stops one and replaces it",
    async () => {
      const cwd = await project("claude");
      const { server, log } = await leglas(cwd, true);
      const began = Date.now();

      const started = await call(server, "generate", {
        surface: "hero",
        brief: "A cooking app",
        count: 3,
      });

      expect(started.status).toBe(202);

      const building = await until(
        server,
        (current) =>
          current.slots.some((slot) => slot.title === "Slow Idea" && slot.state === "building"),
        "the slow direction to be building",
      );

      const slowFile = join(cwd, ".leglas", "variants", "hero", "hero-slow.tsx");

      // Wait until the slow build has written half its file, so the stop has something to undo.
      for (
        let tries = 0;
        tries < 200 && !(await readFile(slowFile, "utf8")).startsWith("// half written");
        tries += 1
      ) {
        await new Promise((resolve) => setTimeout(resolve, 50));
      }

      // Every concept is on the rail the moment the plan lands, before any build finishes.
      const registered = parseJson(await readFile(join(cwd, ".leglas", "previews.json"), "utf8"));

      const titles =
        isJsonRecord(registered) && Array.isArray(registered.previews)
          ? registered.previews.map((entry) => (isJsonRecord(entry) ? entry.title : null))
          : [];

      expect(titles).toEqual(["Plain Idea", "Broken Idea", "Slow Idea"]);

      const slow = required(building.slots.find((slot) => slot.title === "Slow Idea"));
      expect(
        (await call(server, "generate/stop", { id: building.id, slot: slow.key })).status,
      ).toBe(200);

      const settled = await until(
        server,
        (current) => current.state === "done",
        "the generation to settle",
      );

      const byTitle = new Map(settled.slots.map((slot) => [slot.title, slot]));

      expect(byTitle.get("Plain Idea")).toMatchObject({ state: "ready", fixed: false });
      expect(byTitle.get("Broken Idea")).toMatchObject({ state: "ready", fixed: true });
      expect(byTitle.get("Slow Idea")).toMatchObject({ state: "stopped" });
      // The stopped build's half-finished work does not stay on the rail.
      expect(
        await readFile(join(cwd, ".leglas", "variants", "hero", `${slow.key}.tsx`), "utf8"),
      ).toBe("export function HeroSlow() {\n  return null;\n}\n");

      const switchFile = await readFile(
        join(cwd, ".leglas", "variants", "hero", "switch.tsx"),
        "utf8",
      );

      for (const key of ["current", '"hero-a"', '"hero-plain"', '"hero-broken"', '"hero-slow"'])
        expect(switchFile).toContain(`  ${key}:`);

      expect(
        (await call(server, "generate/replace", { id: settled.id, slot: slow.key })).status,
      ).toBe(200);

      const replaced = await until(
        server,
        (current) =>
          current.state === "done" &&
          current.slots.some((slot) => slot.title === "Fresh Idea" && slot.state === "ready"),
        "the replacement",
      );

      const elapsed = Date.now() - began;

      // What Leglas sent: restricted runs at medium effort, and builders told the project's facts.
      const calls = (await readFile(log, "utf8"))
        .trim()
        .split("\n")
        .map((line) => parseJson(line))
        .map((entry) =>
          isJsonRecord(entry) && Array.isArray(entry.args) ? entry.args.map(String) : [],
        );

      for (const args of calls) {
        expect(args).toContain("--restricted");
        expect(args[args.indexOf("--effort") + 1]).toBe("medium");
      }

      const builds = calls.filter(
        (args) => args[args.indexOf("--tools") + 1] === "Read,Write,Edit",
      );

      const plain = required(
        builds.find((args) => args.some((arg) => arg.includes("Plain Idea, Big type"))),
      );

      const prompt = required(plain[plain.indexOf("-p") + 1]);

      expect(prompt).toContain("Leglas read the project for you.");
      expect(prompt).toContain("--accent: #d9542b;");
      expect(prompt).toContain("/photos/plate.jpg");
      expect(prompt).toContain(".leglas/variants/hero/current.tsx");

      // The repeatable artifact: the job as the interface sees it and a screenshot of each ready direction.
      await mkdir(ARTIFACTS, { recursive: true });
      await writeFile(
        join(ARTIFACTS, "summary.json"),
        `${JSON.stringify({ elapsedMs: elapsed, job: replaced, calls: calls.length }, null, 2)}\n`,
      );

      for (const slot of replaced.slots.filter((candidate) => candidate.state === "ready")) {
        const shot = await call(server, "capture", { title: slot.title });
        const file = shot.json.path ?? shot.json.file;

        if (isString(file))
          await copyFile(join(cwd, file), join(ARTIFACTS, `${slot.key}.png`)).catch(() => {});
      }

      // Everything but the fake agents' own sleeps is Leglas: planning, slots, renders and the fix run.
      expect(elapsed).toBeLessThan(30_000);
    },
    START_TIMEOUT_MS * 2,
  );
});

/**
 * A stand-in for one Claude process, driven by the test: a plan run answers
 * with `concepts`; a build either writes its file and exits, or waits until
 * it is killed, and then takes `exitAfterKillMs` to go, as a CLI finishing
 * its own shutdown does.
 */
class FakeChild extends EventEmitter {
  readonly pid = undefined;
  readonly stdout = new PassThrough();
  readonly stderr = new PassThrough();
  exitAfterKillMs = 0;
  private finished = false;

  kill(): boolean {
    setTimeout(() => this.finish(null), this.exitAfterKillMs);

    return true;
  }

  say(result: string): void {
    this.stdout.write(`${JSON.stringify({ type: "result", result })}\n`);
  }

  finish(code: number | null): void {
    if (this.finished) return;
    this.finished = true;
    this.stdout.end();
    this.stderr.end();
    this.emit("close", code, null);
  }
}

type Behaviour = "write" | "hang" | "fail";

function orchestrator(
  cwd: string,
  concepts: object[],
  behaviours: Behaviour[],
  render: (title: string) => Promise<{ errors: readonly string[] } | null>,
  register: GenerationDeps["register"] = async () => ({ ok: true }),
  fixes: "answer" | "hang" = "answer",
) {
  const builds: FakeChild[] = [];
  const spawned: FakeChild[] = [];
  const prompts: string[] = [];
  const announced: ReturnType<ReturnType<typeof createGenerations>["snapshot"]>[] = [];
  let buildIndex = 0;

  const fakeSpawn: RunnerSpawn = (_command, args) => {
    const child = new FakeChild();
    const prompt = args[args.indexOf("-p") + 1] ?? "";
    spawned.push(child);
    prompts.push(prompt);

    if (args[args.indexOf("--tools") + 1] === "") {
      setTimeout(() => {
        child.say(JSON.stringify(concepts));
        child.finish(0);
      }, 5);
    } else if (prompt.startsWith("Leglas rendered ")) {
      // A fix run answers and leaves the file as it was; the render decides.
      builds.push(child);

      if (fixes === "answer") setTimeout(() => child.finish(0), 5);
    } else {
      builds.push(child);
      const behaviour = behaviours[Math.min(buildIndex, behaviours.length - 1)];
      buildIndex += 1;
      const file = /Your file is (\S+)\./.exec(prompt)?.[1] ?? "";
      const name = /component exported as (\w+)\./.exec(prompt)?.[1] ?? "";

      if (behaviour === "fail") {
        setTimeout(() => {
          void writeFile(
            join(cwd, file),
            `export function ${name}() {\n  return <h1>half</div>;\n}\n`,
          ).then(() => child.finish(1));
        }, 5);
      }

      if (behaviour === "write") {
        setTimeout(() => {
          void writeFile(
            join(cwd, file),
            `export function ${name}() {\n  return <h1>${name}</h1>;\n}\n`,
          ).then(() => child.finish(0));
        }, 5);
      }
    }

    return child;
  };

  const generations = createGenerations({
    cwd,
    spawn: fakeSpawn,
    render,
    register,
    unregister: async () => {},
    titles: async () => new Set<string>(),
    // What every nudge would carry to the interface, in order.
    onChange: () => void announced.push(generations.snapshot()),
  });

  return { generations, builds, spawned, prompts, announced };
}

async function settled<T>(read: () => T | undefined, holds: (value: T) => boolean): Promise<T> {
  for (let tries = 0; tries < 400; tries += 1) {
    const value = read();

    if (value !== undefined && holds(value)) return value;
    await new Promise((resolve) => setTimeout(resolve, 10));
  }

  throw new Error("The condition never held.");
}

describe("a generation's lifecycle", () => {
  test("a direction stopped while its page is being rendered stays stopped", async () => {
    const cwd = await project("claude");
    let rendered!: (report: { errors: readonly string[] }) => void;
    const pending = new Promise<{ errors: readonly string[] }>((resolve) => (rendered = resolve));

    const { generations } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      () => pending,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "checking",
    );

    expect(await generations.stop(started.job.id, slot.key)).toBe(true);
    rendered({ errors: [] });
    await new Promise((resolve) => setTimeout(resolve, 50));

    expect(generations.snapshot()[0]?.slots[0]?.state).toBe("stopped");
    expect(await readFile(join(cwd, slot.file), "utf8")).toBe(
      "export function HeroLedger() {\n  return null;\n}\n",
    );
  });

  test("a retry waits for the stopped build's process to be gone", async () => {
    const cwd = await project("claude");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang", "write"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "building",
    );

    await settled(
      () => builds[0],
      () => true,
    );
    required(builds[0]).exitAfterKillMs = 200;

    const stopping = generations.stop(started.job.id, slot.key);

    // The old process is still shutting down: a retry now would race it.
    expect(generations.retry(started.job.id, slot.key)).toBe(false);
    await stopping;
    expect(generations.retry(started.job.id, slot.key)).toBe(true);

    const done = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state !== "building" && value.state !== "checking",
    );

    expect(done).toMatchObject({ state: "ready", failure: null });
  });

  test("a render that outlives a stop and a retry does not speak for the new attempt", async () => {
    const cwd = await project("claude");
    let staleRender!: (report: { errors: readonly string[] }) => void;
    let renders = 0;

    const render = (): Promise<{ errors: readonly string[] }> => {
      renders += 1;

      return renders === 1
        ? new Promise((resolve) => (staleRender = resolve))
        : Promise.resolve({ errors: [] });
    };

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write", "hang"],
      render,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "checking",
    );

    await generations.stop(started.job.id, slot.key);
    expect(generations.retry(started.job.id, slot.key)).toBe(true);
    await settled(
      () => builds[1],
      () => true,
    );

    // The first attempt's render now reports errors: it must neither call the slot ready nor start a fix run.
    staleRender({ errors: ["Uncaught Error: broken"] });
    await new Promise((resolve) => setTimeout(resolve, 50));

    expect(generations.snapshot()[0]?.slots[0]?.state).toBe("building");
    expect(builds).toHaveLength(2);
  });

  test("a replace that loses its slot to a stop and a retry leaves the retry's work alone", async () => {
    const cwd = await project("claude");
    let registered!: () => void;
    let registrations = 0;

    const register = (): Promise<{ ok: boolean }> => {
      registrations += 1;

      // The replace's registration is held open until the test lets it go.
      return registrations === 2
        ? new Promise((resolve) => (registered = () => resolve({ ok: true })))
        : Promise.resolve({ ok: true });
    };

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      register,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(generations.replace(started.job.id, slot.key)).toBe(true);
    await settled(
      () => (registrations === 2 ? true : undefined),
      () => true,
    );
    await generations.stop(started.job.id, slot.key);
    expect(generations.retry(started.job.id, slot.key)).toBe(true);
    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => builds.length === 2 && value.state === "ready",
    );

    // The replace wakes up after the retry finished; the retry's file is the one that stays.
    registered();
    await new Promise((resolve) => setTimeout(resolve, 50));

    expect(builds).toHaveLength(2);
    expect(generations.snapshot()[0]?.slots[0]?.state).toBe("ready");
    expect(await readFile(join(cwd, slot.file), "utf8")).toBe(
      "export function HeroLedger() {\n  return <h1>HeroLedger</h1>;\n}\n",
    );
  });

  test("a stop while the directions go on the rail waits for them and lists them, stopped", async () => {
    const cwd = await project("claude");
    let registered!: () => void;
    let registrations = 0;

    const register = (): Promise<{ ok: boolean }> => {
      registrations += 1;

      return registrations === 1
        ? new Promise((resolve) => (registered = () => resolve({ ok: true })))
        : Promise.resolve({ ok: true });
    };

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      register,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => (registrations === 1 ? true : undefined),
      () => true,
    );
    const stopping = generations.stop(started.job.id);
    let answered = false;

    void stopping.then(() => (answered = true));
    await new Promise((resolve) => setTimeout(resolve, 50));
    // Stopped means the writes already under way are done, so the answer waits for them.
    expect(answered).toBe(false);

    registered();
    expect(await stopping).toBe(true);

    const job = required(generations.snapshot()[0]);

    expect(job.state).toBe("stopped");
    expect(job.slots.map((slot) => slot.state)).toEqual(["stopped"]);
    expect(builds).toHaveLength(0);
  });

  test("closing waits for directions still going on the rail, even after a stop", async () => {
    const cwd = await project("claude");
    let registered!: () => void;
    let registrations = 0;

    const register = (): Promise<{ ok: boolean }> => {
      registrations += 1;

      return registrations === 1
        ? new Promise((resolve) => (registered = () => resolve({ ok: true })))
        : Promise.resolve({ ok: true });
    };

    const { generations } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      register,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => (registrations === 1 ? true : undefined),
      () => true,
    );

    const stopping = generations.stop(started.job.id);
    const closing = generations.close();
    let closed = false;

    void closing.then(() => (closed = true));
    await new Promise((resolve) => setTimeout(resolve, 50));
    // The switch file and the rail are still being written, so the process must not exit yet.
    expect(closed).toBe(false);

    registered();
    await Promise.all([stopping, closing]);
    expect(generations.snapshot()[0]?.slots.map((slot) => slot.state)).toEqual(["stopped"]);
  });

  test("a replace whose registration fails shows the error on the direction", async () => {
    const cwd = await project("claude");
    let registrations = 0;

    const register = (): Promise<{ ok: boolean }> => {
      registrations += 1;

      return registrations === 2
        ? Promise.reject(new Error("could not write the previews file"))
        : Promise.resolve({ ok: true });
    };

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      register,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(generations.replace(started.job.id, slot.key)).toBe(true);

    const failed = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(failed.failure).toEqual({
      code: "unexpected",
      message: "could not write the previews file",
    });
    expect(builds).toHaveLength(1);
  });

  test("a render that throws fails that direction and its retry, not the whole set", async () => {
    const cwd = await project("claude");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => {
        throw new Error("no browser to render with");
      },
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const failed = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(failed.failure).toEqual({ code: "unexpected", message: "no browser to render with" });
    expect(generations.snapshot()[0]?.state).toBe("done");
    expect(generations.retry(started.job.id, failed.key)).toBe(true);

    const again = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => builds.length === 2 && value.state === "failed",
    );

    expect(again.failure?.code).toBe("unexpected");
  });

  test("closing while a page is being rendered starts no fix run and puts the placeholder back", async () => {
    const cwd = await project("claude");
    let rendered!: (report: { errors: readonly string[] }) => void;

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      () => new Promise((resolve) => (rendered = resolve)),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "checking",
    );

    const closing = generations.close();
    // The browser goes with the rest, so the render ends in an error.
    rendered({ errors: ["Target closed"] });
    await closing;

    expect(builds).toHaveLength(1);
    expect(await readFile(join(cwd, slot.file), "utf8")).toBe(
      "export function HeroLedger() {\n  return null;\n}\n",
    );
  });

  test("a retry, a replace or a new set asked for while Leglas closes is refused and writes nothing", async () => {
    const cwd = await project("claude");
    const kept = "export function HeroLedger() {\n  return <p>kept</p>;\n}\n";

    const { generations, spawned } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      async () => ({ errors: [] }),
    );

    const request = {
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude" as const, effort: null, run: null },
    };

    const started = await generations.start(request);

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => spawned.length === 2 && value.state === "building",
    );

    await generations.close();
    // Close has finished waiting, so anything started now could be cut off mid-write.
    await writeFile(join(cwd, slot.file), kept);

    expect(generations.retry(started.job.id, slot.key)).toBe(false);
    expect(generations.replace(started.job.id, slot.key)).toBe(false);
    expect(await generations.start(request)).toEqual({ ok: false, error: "Leglas is closing." });
    await new Promise((resolve) => setTimeout(resolve, 50));
    expect(await readFile(join(cwd, slot.file), "utf8")).toBe(kept);
    expect(spawned).toHaveLength(2);
  });

  test("a set that starts as Leglas closes starts no process", async () => {
    const cwd = await project("claude");

    const { generations, spawned } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
    );

    const starting = generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    await generations.close();
    const started = await starting;

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => generations.snapshot()[0],
      (value) => value.state === "failed",
    );
    expect(spawned).toHaveLength(0);
  });

  test("a page broken by another direction still being written waits for it instead of blaming this one", async () => {
    const cwd = await project("claude");
    const steamFile = join(".leglas", "variants", "hero", "hero-steam.tsx");
    let steamBroken = true;

    const { generations, builds } = orchestrator(
      cwd,
      [
        { key: "ledger", title: "Ledger", idea: "Ruled lines." },
        { key: "steam", title: "Steam", idea: "A pan, close." },
      ],
      ["write", "hang"],
      async (title) => ({
        errors:
          title === "Ledger" && steamBroken
            ? [
                `Failed to load resource: the server responded with a status of 500 (Internal Server Error) (/${steamFile})`,
              ]
            : [],
      }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 2,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "checking",
    );
    // Long enough to look at the page twice, both times blaming Steam's file while Steam is written.
    await new Promise((resolve) => setTimeout(resolve, 2000));
    expect(builds).toHaveLength(2);
    expect(generations.snapshot()[0]?.slots[0]?.state).toBe("checking");

    steamBroken = false;

    const ready = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(ready.fixed).toBe(false);
    expect(builds).toHaveLength(2);
  });

  test("a failed draft goes back to the placeholder, so it cannot break the others' pages", async () => {
    const cwd = await project("claude");

    const { generations } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["fail"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const failed = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    await new Promise((resolve) => setTimeout(resolve, 50));
    expect(await readFile(join(cwd, failed.file), "utf8")).toBe(
      "export function HeroLedger() {\n  return null;\n}\n",
    );
  });

  test("two drafts that fail their render check do not stop the rest", async () => {
    const cwd = await project("claude");

    const { generations } = orchestrator(
      cwd,
      [
        { key: "ledger", title: "Ledger", idea: "Ruled lines." },
        { key: "steam", title: "Steam", idea: "A pan, close." },
        { key: "timer", title: "Timer", idea: "Thirty minutes." },
      ],
      ["write", "write", "hang"],
      async (title) => ({ errors: title === "Timer" ? [] : ["Uncaught Error: still broken"] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 3,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    await settled(
      () => generations.snapshot()[0]?.slots,
      (slots) => slots[0]?.state === "failed" && slots[1]?.state === "failed",
    );
    expect(generations.snapshot()[0]?.slots[2]?.state).toBe("building");
  });

  test("a new idea's start is when it was asked for, not when its build began", async () => {
    const cwd = await project("claude");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["fail", "hang"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const failed = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(generations.replace(started.job.id, failed.key)).toBe(true);
    const asked = generations.snapshot()[0]?.slots[0]?.startedAt;

    // The replacement is planned first, and only then built.
    await settled(
      () => builds[1],
      () => true,
    );
    expect(generations.snapshot()[0]?.slots[0]?.startedAt).toBe(asked);
  });

  test("a generated direction carries its brief and its surface onto the rail", async () => {
    const cwd = await project("claude");
    const registered: AddInput[] = [];

    const { generations } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      async (input) => {
        registered.push(input);

        return { ok: true };
      },
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner in thirty minutes",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(registered).toEqual([
      {
        title: "Ledger",
        url: "/?v-hero=hero-ledger",
        note: "Ruled lines.",
        askedFor: "Dinner in thirty minutes",
        tags: ["Hero"],
      },
    ]);
  });

  /** A stream line in which Claude edits these files. */
  const edits = (...files: string[]) =>
    `${JSON.stringify({ type: "assistant", message: { content: files.map((file) => ({ type: "tool_use", name: "Edit", input: { file_path: file } })) } })}\n`;

  test("a retry in an older set puts back the switch as it is now, not as that set found it", async () => {
    const cwd = await project("claude");
    const switchFile = join(cwd, ".leglas", "variants", "hero", "switch.tsx");

    // The first set's build fails, the second's writes, the retry of the first hangs.
    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["fail", "write", "hang"],
      async () => ({ errors: [] }),
    );

    const ask = () =>
      generations.start({
        surface: "hero",
        brief: "Dinner",
        count: 1,
        agent: { agent: "claude", effort: null, run: null },
      });

    const first = await ask();

    if (!first.ok) throw new Error(first.error);
    await settled(
      () => generations.snapshot()[0],
      (value) => value.state === "done",
    );

    const second = await ask();

    if (!second.ok) throw new Error(second.error);
    await settled(
      () => generations.snapshot()[1],
      (value) => value.state === "done",
    );

    const now = await readFile(switchFile, "utf8");
    expect(now).toContain("hero-ledger-2");

    expect(generations.retry(first.job.id, "hero-ledger")).toBe(true);

    const retry = await settled(
      () => builds[2],
      () => true,
    );

    await writeFile(switchFile, "export function HeroSwitch() {\n  return null;\n}\n");
    retry.stdout.write(edits(switchFile));
    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(await readFile(switchFile, "utf8")).toBe(now);
  });

  test("every file a build strays into is put back, a stylesheet a direction imports among them", async () => {
    const cwd = await project("claude");
    const folder = join(cwd, ".leglas", "variants", "hero");
    const switchFile = join(folder, "switch.tsx");
    const sheet = join(folder, "hero.css");
    await writeFile(sheet, ".hero { color: tomato; }\n");
    await writeFile(join(folder, "current.tsx"), `import "./hero.css";\n${CURRENT}`);

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const build = await settled(
      () => builds[0],
      () => true,
    );

    const planned = await readFile(switchFile, "utf8");
    await writeFile(switchFile, "// tidied\n");
    await writeFile(sheet, "");
    build.stdout.write(edits(switchFile, sheet));

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(slot.failure?.message).toBe(
      "The build edited .leglas/variants/hero/switch.tsx and .leglas/variants/hero/hero.css, which are not its own files, so Leglas stopped it and put them back.",
    );
    expect(await readFile(switchFile, "utf8")).toBe(planned);
    expect(await readFile(sheet, "utf8")).toBe(".hero { color: tomato; }\n");
  });

  test("an edit a stopped build makes on its way out is put back too", async () => {
    const cwd = await project("claude");
    const switchFile = join(cwd, ".leglas", "variants", "hero", "switch.tsx");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const build = await settled(
      () => builds[0],
      () => true,
    );

    const planned = await readFile(switchFile, "utf8");
    // Slow to die, so there is time for one last edit after the stop.
    build.exitAfterKillMs = 200;
    const stopping = generations.stop(started.job.id, "hero-ledger");
    await new Promise((resolve) => setTimeout(resolve, 20));
    await writeFile(switchFile, "// tidied on the way out\n");
    build.stdout.write(edits(switchFile));
    await stopping;

    let content = "";

    for (let tries = 0; tries < 200 && content !== planned; tries += 1) {
      await new Promise((resolve) => setTimeout(resolve, 10));
      content = await readFile(switchFile, "utf8");
    }

    expect(content).toBe(planned);
  });

  test("an edit on a stream's last line, with no newline after it, is still caught", async () => {
    const cwd = await project("claude");
    const switchFile = join(cwd, ".leglas", "variants", "hero", "switch.tsx");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const build = await settled(
      () => builds[0],
      () => true,
    );

    const planned = await readFile(switchFile, "utf8");
    await writeFile(switchFile, "// tidied\n");
    build.stdout.write(edits(switchFile).trimEnd());
    build.finish(0);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(slot.failure?.code).toBe("outside-file");
    expect(await readFile(switchFile, "utf8")).toBe(planned);
  });

  test("a retry read while another build's stray is not yet put back keeps the good switch", async () => {
    const cwd = await project("claude");
    const switchFile = join(cwd, ".leglas", "variants", "hero", "switch.tsx");

    // Ledger hangs, Steam fails at once, and Steam's retry hangs.
    const { generations, builds } = orchestrator(
      cwd,
      [
        { key: "ledger", title: "Ledger", idea: "Ruled lines." },
        { key: "steam", title: "Steam", idea: "A pan." },
      ],
      ["hang", "fail", "hang"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 2,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => generations.snapshot()[0]?.slots[1],
      (value) => value.state === "failed",
    );

    const planned = await readFile(switchFile, "utf8");
    const ledger = builds[0]!;

    // Ledger strays and is slow to die; Steam is retried inside that window.
    ledger.exitAfterKillMs = 400;
    await writeFile(switchFile, "// tidied by Ledger\n");
    ledger.stdout.write(edits(switchFile));
    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.activity !== null,
    );
    expect(generations.retry(started.job.id, "hero-steam")).toBe(true);

    const retry = await settled(
      () => builds[2],
      () => true,
    );

    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    // Steam's retry strays into the switch too, after Ledger's is put back.
    await writeFile(switchFile, "// tidied by Steam\n");
    retry.stdout.write(edits(switchFile));
    await settled(
      () => generations.snapshot()[0]?.slots[1],
      (value) => value.state === "failed",
    );

    expect(await readFile(switchFile, "utf8")).toBe(planned);
  });

  test("a stray into a direction another set is building is named, not put back", async () => {
    const cwd = await project("claude");

    // The first set's build fails, the second set's hangs, the first set's retry hangs.
    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["fail", "hang", "hang"],
      async () => ({ errors: [] }),
    );

    const ask = (brief: string) =>
      generations.start({
        surface: "hero",
        brief,
        count: 1,
        agent: { agent: "claude", effort: null, run: null },
      });

    const first = await ask("Dinner");

    if (!first.ok) throw new Error(first.error);
    await settled(
      () => generations.snapshot()[0],
      (value) => value.state === "done",
    );

    const second = await ask("Supper");

    if (!second.ok) throw new Error(second.error);
    await settled(
      () => builds[1],
      () => true,
    );

    // The second set's slot, still building.
    const secondFile = join(cwd, ".leglas", "variants", "hero", "hero-ledger-2.tsx");
    expect(generations.retry(first.job.id, "hero-ledger")).toBe(true);

    const retry = await settled(
      () => builds[2],
      () => true,
    );

    await writeFile(secondFile, "// half of the second set's draft\n");
    retry.stdout.write(edits(secondFile));

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(slot.failure?.message).toBe(
      "The build edited .leglas/variants/hero/hero-ledger-2.tsx, which is not its own file, so Leglas stopped it. Check .leglas/variants/hero/hero-ledger-2.tsx before trying again.",
    );
    expect(await readFile(secondFile, "utf8")).toBe("// half of the second set's draft\n");
    await generations.close();
  });

  test("a direction whose page breaks because another build strayed waits for the fix instead of failing", async () => {
    const cwd = await project("claude");
    const switchFile = join(cwd, ".leglas", "variants", "hero", "switch.tsx");

    const { generations, builds } = orchestrator(
      cwd,
      [
        { key: "ledger", title: "Ledger", idea: "Ruled lines." },
        { key: "steam", title: "Steam", idea: "A pan." },
      ],
      ["hang", "hang"],
      async () =>
        (await readFile(switchFile, "utf8")).includes("tidied")
          ? { errors: [`ReferenceError: Missing is not defined at ${switchFile}:3:5`] }
          : { errors: [] },
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 2,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => builds[1],
      () => true,
    );
    const [ledger, steam] = [builds[0]!, builds[1]!];

    // Ledger strays and takes a while to die; Steam finishes meanwhile.
    ledger.exitAfterKillMs = 400;
    const planned = await readFile(switchFile, "utf8");
    await writeFile(switchFile, `// tidied\n${planned}`);
    ledger.stdout.write(edits(switchFile));
    // Wait until Ledger's edit has been read.
    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.activity !== null,
    );
    await writeFile(
      join(cwd, ".leglas", "variants", "hero", "hero-steam.tsx"),
      "export function HeroSteam() {\n  return <h1>Steam</h1>;\n}\n",
    );
    steam.finish(0);

    const slots = await settled(
      () => generations.snapshot()[0]?.slots,
      (value) => value.every((slot) => slot.state === "ready" || slot.state === "failed"),
    );

    expect(slots.map((slot) => [slot.title, slot.state, slot.fixed])).toEqual([
      ["Ledger", "failed", false],
      ["Steam", "ready", false],
    ]);
  });

  test("a build that edits the switch file is stopped, and the switch is put back", async () => {
    const cwd = await project("claude");
    const switchFile = join(cwd, ".leglas", "variants", "hero", "switch.tsx");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const build = await settled(
      () => builds[0],
      () => true,
    );

    // As the set wrote it.
    const planned = await readFile(switchFile, "utf8");
    expect(planned).toContain("hero-ledger");

    await writeFile(switchFile, "export function HeroSwitch() {\n  return null;\n}\n");
    build.stdout.write(
      `${JSON.stringify({ type: "assistant", message: { content: [{ type: "tool_use", name: "Edit", input: { file_path: switchFile } }] } })}\n`,
    );

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(slot.failure).toEqual({
      code: "outside-file",
      message:
        "The build edited .leglas/variants/hero/switch.tsx, which is not its own file, so Leglas stopped it and put the file back.",
    });
    expect(await readFile(switchFile, "utf8")).toBe(planned);
  });

  test("a fix run that edits a file a direction imports is stopped, and the file is put back", async () => {
    const cwd = await project("claude");
    // Imported by the current direction.
    const copy = join(cwd, "src", "copy.ts");
    await writeFile(copy, 'export const COPY = { headline: "Dinner tonight" };\n');
    const reports: ((report: { errors: readonly string[] }) => void)[] = [];
    const file = join(cwd, ".leglas", "variants", "hero", "hero-ledger.tsx");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      () => new Promise((resolve) => reports.push(resolve)),
      undefined,
      "hang",
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const build = await settled(
      () => builds[0],
      () => true,
    );

    await writeFile(file, "export function HeroLedger() {\n  return <h1>Ledger</h1>;\n}\n");
    build.finish(0);
    await settled(
      () => reports[0],
      () => true,
    );
    reports[0]!({ errors: ["Transform failed: hero-ledger.tsx:2:3"] });

    const fix = await settled(
      () => builds[1],
      () => true,
    );

    await writeFile(copy, "export const COPY = {};\n");
    fix.stdout.write(
      `${JSON.stringify({ type: "assistant", message: { content: [{ type: "tool_use", name: "Write", input: { file_path: copy } }] } })}\n`,
    );

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(slot.failure?.message).toBe(
      "The build edited src/copy.ts, which is not its own file, so Leglas stopped it and put the file back.",
    );
    expect(await readFile(copy, "utf8")).toBe(
      'export const COPY = { headline: "Dinner tonight" };\n',
    );
    // Still retryable.
    expect(generations.retry(started.job.id, slot.key)).toBe(true);
    await generations.close();
  });

  test("a building direction says what its build is doing", async () => {
    const cwd = await project("claude");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const child = await settled(
      () => builds[0],
      () => true,
    );

    const file = join(cwd, ".leglas", "variants", "hero", "hero-ledger.tsx");

    child.stdout.write(
      `${JSON.stringify({ type: "assistant", message: { content: [{ type: "tool_use", name: "Write", input: { file_path: file, content: "" } }] } })}\n`,
    );

    const building = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.activity !== null,
    );

    expect(building.activity).toBe("editing .leglas/variants/hero/hero-ledger.tsx");
  });

  test("checking starts with no build step left over, and a fix run says what it is doing", async () => {
    const cwd = await project("claude");
    const reports: ((report: { errors: readonly string[] }) => void)[] = [];
    const file = join(cwd, ".leglas", "variants", "hero", "hero-ledger.tsx");

    const edit = (tool: string) =>
      `${JSON.stringify({ type: "assistant", message: { content: [{ type: "tool_use", name: tool, input: { file_path: file } }] } })}\n`;

    const { generations, builds, announced } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      () => new Promise((resolve) => reports.push(resolve)),
      undefined,
      "hang",
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);
    const slot = () => generations.snapshot()[0]?.slots[0];

    const build = await settled(
      () => builds[0],
      () => true,
    );

    build.stdout.write(edit("Write"));
    await settled(slot, (value) => value.activity !== null);
    await writeFile(file, "export function HeroLedger() {\n  return <h1>Ledger</h1>;\n}\n");
    build.finish(0);

    expect(await settled(slot, (value) => value.state === "checking")).toMatchObject({
      activity: null,
    });

    await settled(
      () => reports[0],
      () => true,
    );
    reports[0]!({ errors: ["Transform failed: hero-ledger.tsx:2:3"] });

    const fix = await settled(
      () => builds[1],
      () => true,
    );

    fix.stdout.write(edit("Edit"));

    expect(await settled(slot, (value) => value.activity !== null)).toMatchObject({
      state: "checking",
      activity: "editing .leglas/variants/hero/hero-ledger.tsx",
    });

    fix.finish(0);
    await settled(
      () => reports[1],
      () => true,
    );
    // Opening the page again, the fix run's last step is over too, and the interface is told.
    expect(slot()?.activity).toBeNull();
    expect(announced.at(-1)?.[0]?.slots[0]?.activity).toBeNull();
    reports[1]!({ errors: [] });

    expect(await settled(slot, (value) => value.state === "ready")).toMatchObject({
      activity: null,
      fixed: true,
    });
  });

  test("another direction finishing leaves a fix run's step on its cover", async () => {
    const cwd = await project("claude");
    const reports: ((report: { errors: readonly string[] }) => void)[] = [];
    const folder = join(cwd, ".leglas", "variants", "hero");

    const { generations, builds } = orchestrator(
      cwd,
      [
        { key: "ledger", title: "Ledger", idea: "Ruled lines." },
        { key: "steam", title: "Steam", idea: "A pan." },
      ],
      ["hang", "hang"],
      (title) =>
        title === "Ledger"
          ? new Promise((resolve) => reports.push(resolve))
          : Promise.resolve({ errors: [] }),
      undefined,
      "hang",
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 2,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slots = () => generations.snapshot()[0]?.slots ?? [];
    await settled(
      () => builds[1],
      () => true,
    );
    const [ledger, steam] = [builds[0]!, builds[1]!];

    await writeFile(
      join(folder, "hero-ledger.tsx"),
      "export function HeroLedger() {\n  return <h1>Ledger</h1>;\n}\n",
    );
    ledger.finish(0);
    await settled(
      () => reports[0],
      () => true,
    );
    reports[0]!({ errors: ["Transform failed: hero-ledger.tsx:2:3"] });

    const fix = await settled(
      () => builds[2],
      () => true,
    );

    fix.stdout.write(
      `${JSON.stringify({ type: "assistant", message: { content: [{ type: "tool_use", name: "Edit", input: { file_path: join(folder, "hero-ledger.tsx") } }] } })}\n`,
    );
    await settled(
      () => slots()[0],
      (value) => value.activity !== null,
    );

    await writeFile(
      join(folder, "hero-steam.tsx"),
      "export function HeroSteam() {\n  return <h1>Steam</h1>;\n}\n",
    );
    steam.finish(0);
    await settled(
      () => slots()[1],
      (value) => value.state === "ready",
    );

    expect(slots()[0]).toMatchObject({
      state: "checking",
      activity: "editing .leglas/variants/hero/hero-ledger.tsx",
    });
    await generations.stop(started.job.id);
  });

  test("a planned direction never overwrites a file that is already there", async () => {
    const cwd = await project("claude");
    const own = 'export function HeroImage() {\n  return <img src="/hero.jpg" alt="" />;\n}\n';
    await writeFile(join(cwd, ".leglas", "variants", "hero", "hero-image.tsx"), own);

    const { generations } = orchestrator(
      cwd,
      [{ key: "image", title: "Image", idea: "A photograph." }],
      ["write"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(slot.key).toBe("hero-image-2");
    expect(await readFile(join(cwd, ".leglas", "variants", "hero", "hero-image.tsx"), "utf8")).toBe(
      own,
    );
  });

  test("variations are built from their direction's own file and sit under it on the rail", async () => {
    const cwd = await project("claude");
    const registered: AddInput[] = [];

    const heroA = CURRENT.replace("export function Current()", "export function HeroA()").replace(
      "<footer>Simmer</footer>",
      "<footer>Simmer, again</footer>",
    );

    await writeFile(join(cwd, ".leglas", "variants", "hero", "hero-a.tsx"), heroA);

    const { generations, prompts } = orchestrator(
      cwd,
      [
        { key: "warm", title: "Warm", idea: "The same page in warm light." },
        { key: "tight", title: "Tight", idea: "The same page, denser." },
      ],
      ["write"],
      async () => ({ errors: [] }),
      async (input) => {
        registered.push(input);

        return { ok: true };
      },
    );

    const started = await generations.start({
      surface: "hero",
      brief: "",
      count: 2,
      agent: { agent: "claude", effort: null, run: null },
      basedOn: { title: "Hero A", key: "hero-a", idea: "Ink and a single accent." },
    });

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => generations.snapshot()[0],
      (value) => value.slots.length === 2 && value.slots.every((slot) => slot.state === "ready"),
    );

    expect(registered.map((entry) => [entry.title, entry.basedOn, entry.askedFor])).toEqual([
      ["Warm", "Hero A", undefined],
      ["Tight", "Hero A", undefined],
    ]);

    const builds = prompts.filter((prompt) => prompt.startsWith("Build "));
    expect(builds).toHaveLength(2);

    for (const prompt of builds) {
      expect(prompt).toMatch(
        /^Build this variation of the hero direction "Hero A": (Warm|Tight), /,
      );
      expect(prompt).toContain(
        "Hero A, the direction being varied, is .leglas/variants/hero/hero-a.tsx. Its imports are relative to that file:",
      );
      expect(prompt).toContain("<footer>Simmer, again</footer>");
    }

    // A new idea for one of them is still a variation of Hero A.
    const warm = required(generations.snapshot()[0]?.slots[0]);
    expect(generations.replace(started.job.id, warm.key)).toBe(true);
    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(prompts.find((prompt) => prompt.startsWith("Propose 1 "))).toMatch(
      /^Propose 1 more variation of the hero direction "Hero A" \(Ink and a single accent\)\. It stays recognisably Hero A/,
    );
  });

  test("a direction that failed to build cannot be varied until it is built", async () => {
    const cwd = await project("claude");

    const { generations, spawned } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["fail"],
      async () => ({ errors: [] }),
    );

    const first = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!first.ok) throw new Error(first.error);
    await settled(
      () => generations.snapshot()[0],
      (value) => value.state === "done" && value.slots[0]?.state === "failed",
    );
    const before = spawned.length;

    const varied = await generations.start({
      surface: "hero",
      brief: "",
      count: 2,
      agent: { agent: "claude", effort: null, run: null },
      basedOn: { title: "Ledger", key: "hero-ledger", idea: "Ruled lines." },
    });

    expect(varied).toEqual({
      ok: false,
      error: "Ledger has no finished design yet, so there is nothing to vary. Retry it first.",
    });
    expect(spawned).toHaveLength(before);
  });

  test("two sets asked for at once start only one", async () => {
    const cwd = await project("claude");

    const { generations } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      async () => ({ errors: [] }),
    );

    const ask = () =>
      generations.start({
        surface: "hero",
        brief: "Dinner",
        count: 1,
        agent: { agent: "claude", effort: null, run: null },
      });

    const answers = await Promise.all([ask(), ask()]);

    // Either may win the race; only one may start.
    expect(answers.filter((answer) => answer.ok)).toHaveLength(1);
    expect(generations.snapshot()).toHaveLength(1);
    await generations.close();
  });

  test("a direction that is not in the switch cannot be varied, and nothing starts", async () => {
    const cwd = await project("claude");

    const { generations, spawned } = orchestrator(cwd, [], ["write"], async () => ({ errors: [] }));

    const started = await generations.start({
      surface: "hero",
      brief: "",
      count: 2,
      agent: { agent: "claude", effort: null, run: null },
      basedOn: { title: "Gone", key: "hero-gone", idea: "" },
    });

    expect(started).toEqual({
      ok: false,
      error: "Gone is not a direction of the hero, so Leglas cannot build variations of it.",
    });
    expect(spawned).toHaveLength(0);
    expect(generations.snapshot()).toEqual([]);
  });
});

describe("a set built with Codex", () => {
  /** A Codex home whose config defines servers the ways people write them. */
  async function codexHome(): Promise<string> {
    const home = await mkdtemp(join(tmpdir(), "leglas-codex-home-"));
    cleanups.push(() => rm(home, { recursive: true, force: true }));
    await writeFile(
      join(home, "config.toml"),
      [
        'model = "some-model"',
        "",
        "[mcp_servers.blender]",
        'command = "uvx"',
        "",
        "[mcp_servers.blender.env]",
        'BLENDER = "1"',
        "",
        '[mcp_servers."gmail-organizer"]',
        'url = "http://127.0.0.1:1/mcp"',
        "",
        '[mcp_servers."odd.name"]',
        'url = "http://127.0.0.1:2/mcp"',
        "",
        "[mcp_servers.'paper'] # the design app",
        'url = "http://127.0.0.1:3/mcp"',
        "",
        "[ mcp_servers . spaced ]",
        'url = "http://127.0.0.1:4/mcp"',
        "",
      ].join("\n"),
    );

    return home;
  }

  /** Stands in for `codex exec --json`: its warning item first, then an answer or a written file. */
  /** `strayTo`: the build edits that file first, then hangs. */
  function fakeCodex(cwd: string, fails = false, strayTo: string | null = null) {
    const calls: { command: string; args: string[] }[] = [];
    const announced: string[] = [];

    const spawn: RunnerSpawn = (command, args) => {
      const child = new FakeChild();
      calls.push({ command, args: [...args] });
      const prompt = args.at(-1) ?? "";
      const say = (event: JsonRecord) => child.stdout.write(`${JSON.stringify(event)}\n`);

      setTimeout(() => {
        say({
          type: "item.completed",
          item: { type: "error", message: "Under-development features enabled" },
        });

        if (args.includes("read-only")) {
          say({
            type: "item.completed",
            item: {
              type: "agent_message",
              text: JSON.stringify([{ key: "ledger", title: "Ledger", idea: "Ruled lines." }]),
            },
          });
          child.finish(0);

          return;
        }

        if (fails) {
          child.finish(1);

          return;
        }

        // A fix run answers and leaves the file to the render, as the Claude fake does.
        if (prompt.startsWith("Leglas rendered ")) {
          child.finish(0);

          return;
        }

        const file = /Your file is (\S+)\./.exec(prompt)?.[1] ?? "";
        const name = /component exported as (\w+)\./.exec(prompt)?.[1] ?? "";

        if (strayTo !== null) {
          void writeFile(join(cwd, strayTo), "export const COPY = {};\n").then(() =>
            say({
              type: "item.completed",
              item: {
                type: "file_change",
                changes: [{ path: join(cwd, strayTo), kind: "update" }],
              },
            }),
          );

          return;
        }

        say({
          type: "item.started",
          item: { type: "file_change", changes: [{ path: join(cwd, file), kind: "update" }] },
        });
        setTimeout(() => {
          void writeFile(
            join(cwd, file),
            `export function ${name}() {\n  return <h1>${name}</h1>;\n}\n`,
          ).then(() => child.finish(0));
        }, 20);
      }, 5);

      return child;
    };

    return { calls, announced, spawn };
  }

  async function run(fails = false, brokenOnce = false, strayTo: string | null = null) {
    const cwd = await project("codex");
    const codex = fakeCodex(cwd, fails, strayTo);
    let renders = 0;

    const generations = createGenerations({
      cwd,
      codexHome: await codexHome(),
      spawn: codex.spawn,
      render: async () => {
        renders += 1;

        return {
          errors: brokenOnce && renders === 1 ? ["Transform failed: hero-ledger.tsx:2:3"] : [],
        };
      },
      register: async () => ({ ok: true }),
      unregister: async () => {},
      titles: async () => new Set<string>(),
      onChange: () => {
        const activity = generations.snapshot()[0]?.slots[0]?.activity;

        if (activity !== null && activity !== undefined) codex.announced.push(activity);
      },
    });

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "codex", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready" || value.state === "failed",
    );

    return { ...codex, cwd, job: started.job, slot };
  }

  test("a build that edits a file of the app's own is stopped, and the file is named", async () => {
    const { cwd, slot } = await run(false, false, "src/main.tsx");

    expect(slot.failure).toEqual({
      code: "outside-file",
      message:
        "The build edited src/main.tsx, which is not its own file, so Leglas stopped it. Check src/main.tsx before trying again.",
    });
    // Not kept, so left as the build wrote it.
    expect(await readFile(join(cwd, "src", "main.tsx"), "utf8")).toBe("export const COPY = {};\n");
  });

  test("plans and builds with restricted Codex runs, reading its answer and its steps", async () => {
    const { calls, announced, job, slot } = await run();

    expect(job.agent).toBe("codex");
    expect(slot.state).toBe("ready");
    expect(calls.map((call) => call.command)).toEqual(["codex", "codex"]);

    const [plan, build] = calls.map((call) => call.args.join(" "));
    expect(plan).toContain("exec --json --ephemeral --skip-git-repo-check");
    expect(plan).toContain("-s read-only");
    expect(build).toContain("-s workspace-write");

    for (const args of [plan, build]) {
      expect(args).toContain("-c model_reasoning_effort=medium");
      // A version that lacks a feature ignores it here, where `--disable` would refuse to start.
      expect(args).toContain("-c features.plugins=false");
      expect(args).not.toContain("--disable");
      expect(args).toContain("-c mcp_servers.blender.enabled=false");
      expect(args).toContain("-c mcp_servers.gmail-organizer.enabled=false");
      expect(args).toContain("-c mcp_servers.paper.enabled=false");
      expect(args).not.toContain("odd.name");
    }

    expect(announced).toContain("editing .leglas/variants/hero/hero-ledger.tsx");
  });

  test("switches off exactly the servers its config defines, however they are written", async () => {
    expect(await codexServers(await codexHome())).toEqual([
      "blender",
      "gmail-organizer",
      "paper",
      "spaced",
    ]);
  });

  test("a page that fails its check gets a Codex fix run that may write", async () => {
    const { calls, slot } = await run(false, true);

    expect(slot).toMatchObject({ state: "ready", fixed: true });
    expect(calls.map((call) => call.command)).toEqual(["codex", "codex", "codex"]);

    const fix = calls[2]?.args ?? [];
    expect(fix.at(-1)).toMatch(/^Leglas rendered /);
    expect(fix.join(" ")).toContain("-s workspace-write");
  });

  test("a failed build says Codex failed, not Claude", async () => {
    const { slot } = await run(true);

    expect(slot.failure?.message).toBe(
      "Codex exited with code 1. Its last output is in the Leglas terminal.",
    );
  });

  test("its answer is the last agent message, whatever Codex reports around it", () => {
    const line = (event: JsonRecord) => JSON.stringify(event);

    expect(
      codexResultText([
        line({ type: "item.completed", item: { type: "agent_message", text: "first" } }),
        "2026-09-25T07:54:36Z ERROR codex_api: failed to connect",
        line({ type: "item.completed", item: { type: "agent_message", text: "last" } }),
        line({ type: "item.completed", item: { type: "error", message: "a warning" } }),
        line({ type: "turn.completed", usage: { input_tokens: 1 } }),
      ]),
    ).toBe("last");
    expect(codexResultText([line({ type: "turn.completed" })])).toBeNull();
  });

  test("with no Codex config, no server is named", async () => {
    expect(await codexServers(join(tmpdir(), "leglas-no-codex-home-here"))).toEqual([]);
  });
});
