import { boundPort, required } from "../test-helpers.js";
import { spawn } from "node:child_process";
import { EventEmitter } from "node:events";
import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import http from "node:http";
import { tmpdir } from "node:os";
import { PassThrough } from "node:stream";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { afterAll, describe, expect, test } from "vitest";

import { readProjectFacts } from "./facts.js";
import { createGenerations, type GenerationDeps } from "./generation.js";
import { addSlots } from "./switch-file.js";

import type { RunnerSpawn } from "../agents/runner.js";
import { START_TIMEOUT_MS, findBrowser } from "../capture/browser.js";
import { isJsonRecord, isString, parseJson, type JsonRecord, type JsonValue } from "../json.js";
import { startServer, type RunningServer } from "../server.js";

const ARTIFACTS = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "..",
  "test",
  "artifacts",
  "generation",
);

/** The switch file `leglas new hero` writes, trimmed to what a generation reads and edits. */
const SWITCH = `// Generated by leglas new.
import { Current } from "./current";
import { HeroA } from "./hero-a";

const DIRECTIONS = {
  current: Current,
  "hero-a": HeroA,
} as const;

type Direction = keyof typeof DIRECTIONS;
const FALLBACK: Direction = "current";

export function HeroSwitch() {
  const Direction = DIRECTIONS[FALLBACK];
  return <Direction />;
}
`;

/** A real current direction: what builders are shown as the house style. */
const CURRENT = `import { COPY } from "../../../src/copy";

export function Current() {
  return (
    <section style={{ background: "var(--ink)", color: "white", padding: 64 }}>
      <h1 style={{ fontFamily: "House Sans" }}>{COPY.headline}</h1>
      <p>{COPY.body}</p>
      <a href="#" style={{ color: "var(--accent)" }}>
        {COPY.cta}
      </a>
      <img src="/photos/plate.jpg" alt="" />
      <footer>Simmer</footer>
    </section>
  );
}
`;

const STYLES = `@font-face {
  font-family: "House Sans";
  src: url("/fonts/house.woff2") format("woff2");
}

:root {
  --ink: #101010;
  --accent: #d9542b;
}
`;

/**
 * Stands in for \`claude -p\`. A plan run answers with three concepts, or one
 * for a replacement; a build writes the file its prompt names, where "Broken"
 * writes a marker the dev server turns into a thrown error and "Slow" takes
 * long enough to be stopped; a fix run removes the marker. Every call's
 * arguments are logged so the test can read what Leglas sent.
 */
const FAKE_CLAUDE = `
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
const args = process.argv.slice(2);
const prompt = args[args.indexOf("-p") + 1] ?? "";
const tools = args[args.indexOf("--tools") + 1];
appendFileSync(process.env.FAKE_LOG, JSON.stringify({ args }) + "\\n");
const say = (event) => process.stdout.write(JSON.stringify(event) + "\\n");
const sleep = (ms) => new Promise((done) => setTimeout(done, ms));
say({ type: "system", subtype: "init", session_id: "fake" });
if (tools === "") {
  const one = /^Propose 1 /.test(prompt);
  const concepts = one
    ? [{ key: "fresh", title: "Fresh Idea", idea: "A replacement unlike the others." }]
    : [
        { key: "plain", title: "Plain Idea", idea: "Big type on a plain ground." },
        { key: "broken", title: "Broken Idea", idea: "Writes broken code first." },
        { key: "slow", title: "Slow Idea", idea: "Takes its time." },
      ];
  await sleep(150);
  say({ type: "result", subtype: "success", result: "Here you go:\\n\`\`\`json\\n" + JSON.stringify(concepts) + "\\n\`\`\`" });
  process.exit(0);
}
const fix = /^Leglas rendered (\\S+) and the page reported/.exec(prompt);
if (fix) {
  writeFileSync(fix[1], readFileSync(fix[1], "utf8").replace("// broken\\n", ""));
  say({ type: "result", subtype: "success", result: "fixed" });
  process.exit(0);
}
const file = /Your file is (\\S+)\\./.exec(prompt)[1];
const name = /component exported as (\\w+)\\./.exec(prompt)[1];
const title = /direction for the \\w+: ([^,]+),/.exec(prompt)[1];
readFileSync(file, "utf8");
if (title.startsWith("Slow")) writeFileSync(file, "// half written, as a stopped build leaves it\\n");
await sleep(title.startsWith("Slow") ? 20000 : 300);
const marker = title.startsWith("Broken") ? "// broken\\n" : "";
writeFileSync(file, marker + "// render: " + title + "\\nexport function " + name + "() {\\n  return <h1>" + title + "</h1>;\\n}\\n");
say({ type: "result", subtype: "success", result: "written" });
`;

const cleanups: (() => Promise<void>)[] = [];

afterAll(async () => {
  for (const cleanup of cleanups.splice(0).reverse()) await cleanup();
});

/** A project with a mounted hero switch, a stylesheet with tokens and one photograph. */
async function project(agent: string): Promise<string> {
  const cwd = await mkdtemp(join(tmpdir(), "leglas-generation-"));
  cleanups.push(() => rm(cwd, { recursive: true, force: true }));
  const variants = join(cwd, ".leglas", "variants", "hero");
  await mkdir(variants, { recursive: true });
  await mkdir(join(cwd, "src"), { recursive: true });
  await mkdir(join(cwd, "public", "photos"), { recursive: true });

  await writeFile(
    join(cwd, "package.json"),
    JSON.stringify({ dependencies: { react: "^19.2.0" }, devDependencies: { vite: "^7.1.0" } }),
  );

  await writeFile(join(cwd, "index.html"), '<script type="module" src="/src/main.tsx"></script>\n');
  await writeFile(join(cwd, "src", "main.tsx"), 'import "./styles.css";\n');
  await writeFile(join(cwd, "src", "styles.css"), STYLES);
  await writeFile(join(cwd, "public", "photos", "plate.jpg"), "not really a jpeg");
  await writeFile(join(variants, "switch.tsx"), SWITCH);
  await writeFile(join(variants, "current.tsx"), CURRENT);
  await writeFile(join(variants, "hero-a.tsx"), "export function HeroA() {\n  return null;\n}\n");
  await writeFile(join(cwd, ".leglas", "watch.json"), JSON.stringify({ agent }));

  return cwd;
}

/**
 * The app: renders a direction's file by its \`// render:\` line, and throws
 * for a file still carrying the broken marker, the way a transform error
 * reaches the page.
 */
async function devServer(cwd: string): Promise<number> {
  const server = http.createServer((req, res) => {
    void (async () => {
      const key = new URL(req.url ?? "/", "http://x").searchParams.get("v-hero") ?? "current";
      const source = await readFile(join(cwd, ".leglas", "variants", "hero", "switch.tsx"), "utf8");
      const name = new RegExp(`"?${key}"?:\\s*(\\w+)`).exec(source)?.[1] ?? "";

      const from =
        new RegExp(`import \\{ ${name} \\} from "\\./([^"]+)"`).exec(source)?.[1] ?? "current";

      const file = await readFile(
        join(cwd, ".leglas", "variants", "hero", `${from}.tsx`),
        "utf8",
      ).catch(() => "");

      const words = /\/\/ render: (.+)/.exec(file)?.[1] ?? "";

      const body = file.includes("// broken")
        ? '<script>throw new Error("Transform failed: unterminated JSX")</script>'
        : `<h1 style="font:48px system-ui;margin:48px">${words}</h1>`;

      res.writeHead(200, { "content-type": "text/html; charset=utf-8" });
      res.end(`<!doctype html><html><body style="margin:0;background:#fff">${body}</body></html>`);
    })();
  });

  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  cleanups.push(
    () =>
      new Promise<void>((resolve) => {
        server.closeAllConnections();
        server.close(() => resolve());
      }),
  );

  return boundPort(server);
}

async function leglas(
  cwd: string,
  withBrowser: boolean,
): Promise<{ server: RunningServer; log: string }> {
  const fake = join(cwd, "..", `${cwd.split("/").pop() ?? "x"}-fake-claude.mjs`);
  const log = `${fake}.log`;
  await writeFile(fake, FAKE_CLAUDE);
  await writeFile(log, "");
  cleanups.push(() => rm(fake, { force: true }));
  cleanups.push(() => rm(log, { force: true }));

  const fakeSpawn: RunnerSpawn = (_command, args, options) =>
    spawn(process.execPath, [fake, ...args], {
      ...options,
      env: { ...process.env, FAKE_LOG: log },
    });

  const serverOptions: Parameters<typeof startServer>[0] = {
    config: { devServer: `http://127.0.0.1:${await devServer(cwd)}`, previews: [] },
    cwd,
    port: 0,
    codexAppServer: null,
    claudeAgentSession: null,
    detectTunnels: async () => [],
    generationSpawn: fakeSpawn,
  };

  // Refusals need no browser; only the end-to-end run renders anything.
  if (!withBrowser)
    serverOptions.pool = { acquire: async () => null, reason: () => "none", close: async () => {} };
  const server = await startServer(serverOptions);

  cleanups.push(() => server.close());

  return { server, log };
}

async function call(
  server: RunningServer,
  path: string,
  body?: JsonRecord,
): Promise<{ status: number; json: JsonRecord }> {
  const response = await fetch(`http://127.0.0.1:${server.port}/leglas/api/${path}`, {
    method: body === undefined ? "GET" : "POST",
    headers:
      body === undefined
        ? {}
        : { "content-type": "application/json", origin: `http://127.0.0.1:${server.port}` },
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  const json = parseJson(await response.text());

  return { status: response.status, json: isJsonRecord(json) ? json : {} };
}

type Job = {
  id: string;
  state: string;
  slots: { key: string; title: string; state: string; fixed: boolean }[];
};

function readJob(value: JsonValue | undefined): Job | null {
  if (
    !isJsonRecord(value) ||
    !isString(value.id) ||
    !isString(value.state) ||
    !Array.isArray(value.slots)
  )
    return null;

  return {
    id: value.id,
    state: value.state,
    slots: value.slots.filter(isJsonRecord).map((slot) => ({
      key: String(slot.key),
      title: String(slot.title),
      state: String(slot.state),
      fixed: slot.fixed === true,
    })),
  };
}

async function job(server: RunningServer): Promise<Job | null> {
  const { json } = await call(server, "generate");

  return Array.isArray(json.jobs) ? readJob(json.jobs.at(-1)) : null;
}

async function until(
  server: RunningServer,
  holds: (current: Job) => boolean,
  what: string,
): Promise<Job> {
  const deadline = Date.now() + 45_000;

  while (Date.now() < deadline) {
    const current = await job(server);

    if (current !== null && holds(current)) return current;
    await new Promise((resolve) => setTimeout(resolve, 100));
  }

  throw new Error(`Timed out waiting for ${what}: ${JSON.stringify(await job(server))}`);
}

describe("a switch file gaining slots", () => {
  test("keeps every direction it had and adds one import and entry per slot", () => {
    const result = addSlots(SWITCH, [{ key: "hero-plain", name: "HeroPlain" }]);

    expect(result).toContain(
      'import { HeroA } from "./hero-a";\nimport { HeroPlain } from "./hero-plain";\n',
    );
    expect(result).toContain(
      'const DIRECTIONS = {\n  current: Current,\n  "hero-a": HeroA,\n  "hero-plain": HeroPlain,\n} as const;',
    );
  });
});

describe("the facts a builder is given", () => {
  test("come from the project's stylesheet, public images and current direction", async () => {
    const cwd = await project("claude");
    const facts = await readProjectFacts(cwd, ".leglas/variants/hero/switch.tsx");

    expect(facts.dependencies).toEqual(["react"]);
    expect(facts.stylesheet?.path).toBe("src/styles.css");
    expect(facts.stylesheet?.fonts).toEqual(["House Sans"]);
    expect(facts.stylesheet?.tokens).toContain("--accent: #d9542b;");
    expect(facts.images).toEqual(["/photos/plate.jpg"]);
    expect(facts.example?.path).toBe(".leglas/variants/hero/current.tsx");
  });
});

describe("starting a generation", () => {
  test("is refused, with the reason, for an agent Leglas cannot hold to time", async () => {
    const { server } = await leglas(await project("cursor"), false);

    const started = await call(server, "generate", {
      surface: "hero",
      brief: "Dinner apps",
      count: 3,
    });

    expect(started.status).toBe(422);
    expect(String(started.json.error)).toContain("runs on Claude");
  });

  test("is refused for a surface with no switch, naming the command that makes one", async () => {
    const { server } = await leglas(await project("claude"), false);

    const started = await call(server, "generate", {
      surface: "pricing",
      brief: "Plans",
      count: 3,
    });

    expect(started.status).toBe(422);
    expect(String(started.json.error)).toContain("leglas new pricing --from");
  });
});

describe.skipIf(findBrowser() === null)("a generation, end to end", () => {
  test.skipIf(process.env.CODEX_SANDBOX === "seatbelt")(
    "plans, builds all at once, repairs a broken direction, stops one and replaces it",
    async () => {
      const cwd = await project("claude");
      const { server, log } = await leglas(cwd, true);
      const began = Date.now();

      const started = await call(server, "generate", {
        surface: "hero",
        brief: "A cooking app",
        count: 3,
      });

      expect(started.status).toBe(202);

      const building = await until(
        server,
        (current) =>
          current.slots.some((slot) => slot.title === "Slow Idea" && slot.state === "building"),
        "the slow direction to be building",
      );

      const slowFile = join(cwd, ".leglas", "variants", "hero", "hero-slow.tsx");

      // Wait until the slow build has written half its file, so the stop has something to undo.
      for (
        let tries = 0;
        tries < 200 && !(await readFile(slowFile, "utf8")).startsWith("// half written");
        tries += 1
      ) {
        await new Promise((resolve) => setTimeout(resolve, 50));
      }

      // Every concept is on the rail the moment the plan lands, before any build finishes.
      const registered = parseJson(await readFile(join(cwd, ".leglas", "previews.json"), "utf8"));

      const titles =
        isJsonRecord(registered) && Array.isArray(registered.previews)
          ? registered.previews.map((entry) => (isJsonRecord(entry) ? entry.title : null))
          : [];

      expect(titles).toEqual(["Plain Idea", "Broken Idea", "Slow Idea"]);

      const slow = required(building.slots.find((slot) => slot.title === "Slow Idea"));
      expect(
        (await call(server, "generate/stop", { id: building.id, slot: slow.key })).status,
      ).toBe(200);

      const settled = await until(
        server,
        (current) => current.state === "done",
        "the generation to settle",
      );

      const byTitle = new Map(settled.slots.map((slot) => [slot.title, slot]));

      expect(byTitle.get("Plain Idea")).toMatchObject({ state: "ready", fixed: false });
      expect(byTitle.get("Broken Idea")).toMatchObject({ state: "ready", fixed: true });
      expect(byTitle.get("Slow Idea")).toMatchObject({ state: "stopped" });
      // The stopped build's half-finished work does not stay on the rail.
      expect(
        await readFile(join(cwd, ".leglas", "variants", "hero", `${slow.key}.tsx`), "utf8"),
      ).toBe("export function HeroSlow() {\n  return null;\n}\n");

      const switchFile = await readFile(
        join(cwd, ".leglas", "variants", "hero", "switch.tsx"),
        "utf8",
      );

      for (const key of ["current", '"hero-a"', '"hero-plain"', '"hero-broken"', '"hero-slow"'])
        expect(switchFile).toContain(`  ${key}:`);

      expect(
        (await call(server, "generate/replace", { id: settled.id, slot: slow.key })).status,
      ).toBe(200);

      const replaced = await until(
        server,
        (current) =>
          current.state === "done" &&
          current.slots.some((slot) => slot.title === "Fresh Idea" && slot.state === "ready"),
        "the replacement",
      );

      const elapsed = Date.now() - began;

      // What Leglas sent: restricted runs at medium effort, and builders told the project's facts.
      const calls = (await readFile(log, "utf8"))
        .trim()
        .split("\n")
        .map((line) => parseJson(line))
        .map((entry) =>
          isJsonRecord(entry) && Array.isArray(entry.args) ? entry.args.map(String) : [],
        );

      for (const args of calls) {
        expect(args).toContain("--restricted");
        expect(args[args.indexOf("--effort") + 1]).toBe("medium");
      }

      const builds = calls.filter(
        (args) => args[args.indexOf("--tools") + 1] === "Read,Write,Edit",
      );

      const plain = required(
        builds.find((args) => args.some((arg) => arg.includes("Plain Idea, Big type"))),
      );

      const prompt = required(plain[plain.indexOf("-p") + 1]);

      expect(prompt).toContain("Leglas read the project for you.");
      expect(prompt).toContain("--accent: #d9542b;");
      expect(prompt).toContain("/photos/plate.jpg");
      expect(prompt).toContain(".leglas/variants/hero/current.tsx");

      // The repeatable artifact: the job as the interface sees it and a screenshot of each ready direction.
      await mkdir(ARTIFACTS, { recursive: true });
      await writeFile(
        join(ARTIFACTS, "summary.json"),
        `${JSON.stringify({ elapsedMs: elapsed, job: replaced, calls: calls.length }, null, 2)}\n`,
      );

      for (const slot of replaced.slots.filter((candidate) => candidate.state === "ready")) {
        const shot = await call(server, "capture", { title: slot.title });
        const file = shot.json.path ?? shot.json.file;

        if (isString(file))
          await copyFile(join(cwd, file), join(ARTIFACTS, `${slot.key}.png`)).catch(() => {});
      }

      // Everything but the fake agents' own sleeps is Leglas: planning, slots, renders and the fix run.
      expect(elapsed).toBeLessThan(30_000);
    },
    START_TIMEOUT_MS * 2,
  );
});

/**
 * A stand-in for one Claude process, driven by the test: a plan run answers
 * with `concepts`; a build either writes its file and exits, or waits until
 * it is killed, and then takes `exitAfterKillMs` to go, as a CLI finishing
 * its own shutdown does.
 */
class FakeChild extends EventEmitter {
  readonly pid = undefined;
  readonly stdout = new PassThrough();
  readonly stderr = new PassThrough();
  exitAfterKillMs = 0;
  private finished = false;

  kill(): boolean {
    setTimeout(() => this.finish(null), this.exitAfterKillMs);

    return true;
  }

  say(result: string): void {
    this.stdout.write(`${JSON.stringify({ type: "result", result })}\n`);
  }

  finish(code: number | null): void {
    if (this.finished) return;
    this.finished = true;
    this.stdout.end();
    this.stderr.end();
    this.emit("close", code, null);
  }
}

type Behaviour = "write" | "hang";

function orchestrator(
  cwd: string,
  concepts: object[],
  behaviours: Behaviour[],
  render: (title: string) => Promise<{ errors: readonly string[] } | null>,
  register: GenerationDeps["register"] = async () => ({ ok: true }),
) {
  const builds: FakeChild[] = [];
  const spawned: FakeChild[] = [];
  let buildIndex = 0;

  const fakeSpawn: RunnerSpawn = (_command, args) => {
    const child = new FakeChild();
    const prompt = args[args.indexOf("-p") + 1] ?? "";
    spawned.push(child);

    if (args[args.indexOf("--tools") + 1] === "") {
      setTimeout(() => {
        child.say(JSON.stringify(concepts));
        child.finish(0);
      }, 5);
    } else {
      builds.push(child);
      const behaviour = behaviours[Math.min(buildIndex, behaviours.length - 1)];
      buildIndex += 1;
      const file = /Your file is (\S+)\./.exec(prompt)?.[1] ?? "";
      const name = /component exported as (\w+)\./.exec(prompt)?.[1] ?? "";

      if (behaviour === "write") {
        setTimeout(() => {
          void writeFile(
            join(cwd, file),
            `export function ${name}() {\n  return <h1>${name}</h1>;\n}\n`,
          ).then(() => child.finish(0));
        }, 5);
      }
    }

    return child;
  };

  const generations = createGenerations({
    cwd,
    spawn: fakeSpawn,
    render,
    register,
    unregister: async () => {},
    titles: async () => new Set<string>(),
    onChange: () => {},
  });

  return { generations, builds, spawned };
}

async function settled<T>(read: () => T | undefined, holds: (value: T) => boolean): Promise<T> {
  for (let tries = 0; tries < 400; tries += 1) {
    const value = read();

    if (value !== undefined && holds(value)) return value;
    await new Promise((resolve) => setTimeout(resolve, 10));
  }

  throw new Error("The condition never held.");
}

describe("a generation's lifecycle", () => {
  test("a direction stopped while its page is being rendered stays stopped", async () => {
    const cwd = await project("claude");
    let rendered!: (report: { errors: readonly string[] }) => void;
    const pending = new Promise<{ errors: readonly string[] }>((resolve) => (rendered = resolve));

    const { generations } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      () => pending,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "checking",
    );

    expect(await generations.stop(started.job.id, slot.key)).toBe(true);
    rendered({ errors: [] });
    await new Promise((resolve) => setTimeout(resolve, 50));

    expect(generations.snapshot()[0]?.slots[0]?.state).toBe("stopped");
    expect(await readFile(join(cwd, slot.file), "utf8")).toBe(
      "export function HeroLedger() {\n  return null;\n}\n",
    );
  });

  test("a retry waits for the stopped build's process to be gone", async () => {
    const cwd = await project("claude");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang", "write"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "building",
    );

    await settled(
      () => builds[0],
      () => true,
    );
    required(builds[0]).exitAfterKillMs = 200;

    const stopping = generations.stop(started.job.id, slot.key);

    // The old process is still shutting down: a retry now would race it.
    expect(generations.retry(started.job.id, slot.key)).toBe(false);
    await stopping;
    expect(generations.retry(started.job.id, slot.key)).toBe(true);

    const done = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state !== "building" && value.state !== "checking",
    );

    expect(done).toMatchObject({ state: "ready", failure: null });
  });

  test("a render that outlives a stop and a retry does not speak for the new attempt", async () => {
    const cwd = await project("claude");
    let staleRender!: (report: { errors: readonly string[] }) => void;
    let renders = 0;

    const render = (): Promise<{ errors: readonly string[] }> => {
      renders += 1;

      return renders === 1
        ? new Promise((resolve) => (staleRender = resolve))
        : Promise.resolve({ errors: [] });
    };

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write", "hang"],
      render,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "checking",
    );

    await generations.stop(started.job.id, slot.key);
    expect(generations.retry(started.job.id, slot.key)).toBe(true);
    await settled(
      () => builds[1],
      () => true,
    );

    // The first attempt's render now reports errors: it must neither call the slot ready nor start a fix run.
    staleRender({ errors: ["Uncaught Error: broken"] });
    await new Promise((resolve) => setTimeout(resolve, 50));

    expect(generations.snapshot()[0]?.slots[0]?.state).toBe("building");
    expect(builds).toHaveLength(2);
  });

  test("a replace that loses its slot to a stop and a retry leaves the retry's work alone", async () => {
    const cwd = await project("claude");
    let registered!: () => void;
    let registrations = 0;

    const register = (): Promise<{ ok: boolean }> => {
      registrations += 1;

      // The replace's registration is held open until the test lets it go.
      return registrations === 2
        ? new Promise((resolve) => (registered = () => resolve({ ok: true })))
        : Promise.resolve({ ok: true });
    };

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      register,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(generations.replace(started.job.id, slot.key)).toBe(true);
    await settled(
      () => (registrations === 2 ? true : undefined),
      () => true,
    );
    await generations.stop(started.job.id, slot.key);
    expect(generations.retry(started.job.id, slot.key)).toBe(true);
    await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => builds.length === 2 && value.state === "ready",
    );

    // The replace wakes up after the retry finished; the retry's file is the one that stays.
    registered();
    await new Promise((resolve) => setTimeout(resolve, 50));

    expect(builds).toHaveLength(2);
    expect(generations.snapshot()[0]?.slots[0]?.state).toBe("ready");
    expect(await readFile(join(cwd, slot.file), "utf8")).toBe(
      "export function HeroLedger() {\n  return <h1>HeroLedger</h1>;\n}\n",
    );
  });

  test("a stop while the directions go on the rail waits for them and lists them, stopped", async () => {
    const cwd = await project("claude");
    let registered!: () => void;
    let registrations = 0;

    const register = (): Promise<{ ok: boolean }> => {
      registrations += 1;

      return registrations === 1
        ? new Promise((resolve) => (registered = () => resolve({ ok: true })))
        : Promise.resolve({ ok: true });
    };

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      register,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => (registrations === 1 ? true : undefined),
      () => true,
    );
    const stopping = generations.stop(started.job.id);
    let answered = false;

    void stopping.then(() => (answered = true));
    await new Promise((resolve) => setTimeout(resolve, 50));
    // Stopped means the writes already under way are done, so the answer waits for them.
    expect(answered).toBe(false);

    registered();
    expect(await stopping).toBe(true);

    const job = required(generations.snapshot()[0]);

    expect(job.state).toBe("stopped");
    expect(job.slots.map((slot) => slot.state)).toEqual(["stopped"]);
    expect(builds).toHaveLength(0);
  });

  test("closing waits for directions still going on the rail, even after a stop", async () => {
    const cwd = await project("claude");
    let registered!: () => void;
    let registrations = 0;

    const register = (): Promise<{ ok: boolean }> => {
      registrations += 1;

      return registrations === 1
        ? new Promise((resolve) => (registered = () => resolve({ ok: true })))
        : Promise.resolve({ ok: true });
    };

    const { generations } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      register,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => (registrations === 1 ? true : undefined),
      () => true,
    );

    const stopping = generations.stop(started.job.id);
    const closing = generations.close();
    let closed = false;

    void closing.then(() => (closed = true));
    await new Promise((resolve) => setTimeout(resolve, 50));
    // The switch file and the rail are still being written, so the process must not exit yet.
    expect(closed).toBe(false);

    registered();
    await Promise.all([stopping, closing]);
    expect(generations.snapshot()[0]?.slots.map((slot) => slot.state)).toEqual(["stopped"]);
  });

  test("a replace whose registration fails shows the error on the direction", async () => {
    const cwd = await project("claude");
    let registrations = 0;

    const register = (): Promise<{ ok: boolean }> => {
      registrations += 1;

      return registrations === 2
        ? Promise.reject(new Error("could not write the previews file"))
        : Promise.resolve({ ok: true });
    };

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
      register,
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(generations.replace(started.job.id, slot.key)).toBe(true);

    const failed = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(failed.failure).toEqual({
      code: "unexpected",
      message: "could not write the previews file",
    });
    expect(builds).toHaveLength(1);
  });

  test("a render that throws fails that direction and its retry, not the whole set", async () => {
    const cwd = await project("claude");

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => {
        throw new Error("no browser to render with");
      },
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const failed = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "failed",
    );

    expect(failed.failure).toEqual({ code: "unexpected", message: "no browser to render with" });
    expect(generations.snapshot()[0]?.state).toBe("done");
    expect(generations.retry(started.job.id, failed.key)).toBe(true);

    const again = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => builds.length === 2 && value.state === "failed",
    );

    expect(again.failure?.code).toBe("unexpected");
  });

  test("closing while a page is being rendered starts no fix run and puts the placeholder back", async () => {
    const cwd = await project("claude");
    let rendered!: (report: { errors: readonly string[] }) => void;

    const { generations, builds } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      () => new Promise((resolve) => (rendered = resolve)),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "checking",
    );

    const closing = generations.close();
    // The browser goes with the rest, so the render ends in an error.
    rendered({ errors: ["Target closed"] });
    await closing;

    expect(builds).toHaveLength(1);
    expect(await readFile(join(cwd, slot.file), "utf8")).toBe(
      "export function HeroLedger() {\n  return null;\n}\n",
    );
  });

  test("a retry, a replace or a new set asked for while Leglas closes is refused and writes nothing", async () => {
    const cwd = await project("claude");
    const kept = "export function HeroLedger() {\n  return <p>kept</p>;\n}\n";

    const { generations, spawned } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["hang"],
      async () => ({ errors: [] }),
    );

    const request = {
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude" as const, effort: null, run: null },
    };

    const started = await generations.start(request);

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => spawned.length === 2 && value.state === "building",
    );

    await generations.close();
    // Close has finished waiting, so anything started now could be cut off mid-write.
    await writeFile(join(cwd, slot.file), kept);

    expect(generations.retry(started.job.id, slot.key)).toBe(false);
    expect(generations.replace(started.job.id, slot.key)).toBe(false);
    expect(await generations.start(request)).toEqual({ ok: false, error: "Leglas is closing." });
    await new Promise((resolve) => setTimeout(resolve, 50));
    expect(await readFile(join(cwd, slot.file), "utf8")).toBe(kept);
    expect(spawned).toHaveLength(2);
  });

  test("a set that starts as Leglas closes starts no process", async () => {
    const cwd = await project("claude");

    const { generations, spawned } = orchestrator(
      cwd,
      [{ key: "ledger", title: "Ledger", idea: "Ruled lines." }],
      ["write"],
      async () => ({ errors: [] }),
    );

    const starting = generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    await generations.close();
    const started = await starting;

    if (!started.ok) throw new Error(started.error);
    await settled(
      () => generations.snapshot()[0],
      (value) => value.state === "failed",
    );
    expect(spawned).toHaveLength(0);
  });

  test("a planned direction never overwrites a file that is already there", async () => {
    const cwd = await project("claude");
    const own = 'export function HeroImage() {\n  return <img src="/hero.jpg" alt="" />;\n}\n';
    await writeFile(join(cwd, ".leglas", "variants", "hero", "hero-image.tsx"), own);

    const { generations } = orchestrator(
      cwd,
      [{ key: "image", title: "Image", idea: "A photograph." }],
      ["write"],
      async () => ({ errors: [] }),
    );

    const started = await generations.start({
      surface: "hero",
      brief: "Dinner",
      count: 1,
      agent: { agent: "claude", effort: null, run: null },
    });

    if (!started.ok) throw new Error(started.error);

    const slot = await settled(
      () => generations.snapshot()[0]?.slots[0],
      (value) => value.state === "ready",
    );

    expect(slot.key).toBe("hero-image-2");
    expect(await readFile(join(cwd, ".leglas", "variants", "hero", "hero-image.tsx"), "utf8")).toBe(
      own,
    );
  });
});
